//! The upgrade acceptance gate's fixture substrate.
//!
//! ROI P1 "Versioning, compatibility & safe rollout" — "The gate that makes
//! continuous bumps safe" (operator, 2026-08-31).
//!
//! # Why this crate exists
//!
//! Continuous version bumps are only safe if EVERY new image is proven to boot
//! against state a PRIOR binary version actually produced. This crate is that
//! proof's substrate. It has two halves, and the strict separation between them
//! is the whole point:
//!
//! * [`prior_version`] is the **earlier binary version**. Its
//!   [`prior_version::run_against_scratch_cell`] stands up a scratch cell and
//!   drives it exactly as a shipped older `pillar` would: it enrolls a real
//!   user, seals the cell key with the *old* AEAD algorithm
//!   ([`pillar_crypto::AeadAlgorithm::ChaCha20Poly1305V1`]) rather than today's
//!   default, writes real events into a durable streaming DB, and mints a real
//!   trust artifact. It records the ground truth it observed —
//!   [`CapturedCellState`] — which is the ONLY thing that crosses the version
//!   boundary. Nothing here reaches for a current-default; every value is
//!   captured as the old binary would have captured it.
//!
//! * The gate itself lives in `tests/upgrade_acceptance.rs`. It represents the
//!   **new binary** (this workspace's current code) and boots against a
//!   [`CapturedCellState`] the prior stage produced, asserting every ROI-named
//!   invariant holds across the version boundary.
//!
//! The fixture is therefore GENERATED by an earlier stage of the same test, not
//! hand-authored: [`CapturedCellState`] can only be obtained by actually running
//! the prior-version build against a scratch cell. A corrupted capture (the
//! negative path the gate also asserts) is produced by [`CapturedCellState`]'s
//! own tampering helpers, so the gate proves it FAILS closed on bad input as
//! well as PASSING on good input.

#![allow(clippy::module_name_repetitions)]

use pillar_crypto::{
    Ciphertext, SealingPublicKey, SealingSecretKey, SigningPublicKey, SigningSecretKey,
    SymmetricKey,
};
use pillar_streamdb::{Cid, HeadRecord, MerkleRoot, SegmentSource, SignedSegment, Visibility};

/// The complete, REAL cell state an earlier-version binary produced against a
/// scratch cell — the fixture the new binary is booted against.
///
/// Every field is genuine output of the prior stage (see
/// [`prior_version::run_against_scratch_cell`]); none is hand-authored. Crossing
/// the version boundary as plain captured data (not a live object) is exactly
/// what a real upgrade does: the new binary meets only the bytes the old one
/// left behind.
pub struct CapturedCellState {
    /// The cell / stream owner's signing public key (a real ed25519 key).
    pub owner_pub: SigningPublicKey,
    /// The head record the prior binary published for the owner's stream —
    /// resolved out of band exactly as a rehydrating node would.
    pub head: HeadRecord,
    /// The prior binary's content store, exposed as the backfill substrate a
    /// rehydrating new binary reads pinned segments from.
    segments: SegmentStore,
    /// The materialized view root the prior binary observed after all its
    /// writes — the value the new binary must reconverge to bit-for-bit.
    pub view_root_before: MerkleRoot,
    /// The Cid of the sealed segment-signing key (sealed to the node's custody
    /// key), pinned to the store — recovered by the new binary to prove write
    /// capability survives the upgrade.
    pub sealed_signing_key_cid: Cid,
    /// The node's custody sealing key pair. Only the public half ever went to
    /// the store; the secret is custody-held and used to unseal.
    pub node_custody_pub: SealingPublicKey,
    /// The custody-held secret half of the node sealing key (never stored).
    pub node_custody_secret: SealingSecretKey,
    /// The sealed CELL KEY the prior binary produced, sealed with the OLD AEAD
    /// algorithm tag ([`pillar_crypto::AeadAlgorithm::ChaCha20Poly1305V1`]).
    /// The new binary must still decrypt it (reading the algorithm off the
    /// ciphertext's own inline tag) back to [`Self::cell_key_plaintext`].
    pub sealed_cell_key: Ciphertext,
    /// The symmetric key the old-algorithm ciphertext was sealed under — the
    /// cell key custody would hold. The new binary uses it to open
    /// [`Self::sealed_cell_key`].
    pub cell_key: SymmetricKey,
    /// The associated data bound into the sealed cell key.
    pub cell_key_aad: Vec<u8>,
    /// The plaintext the sealed cell key must decrypt back to.
    pub cell_key_plaintext: Vec<u8>,
    /// The identity of the real user the prior binary enrolled, plus the device
    /// they log in with — the new binary re-runs the login and must succeed.
    pub user: CapturedUser,
    /// The compat surface versions the prior binary DECLARED while running.
    /// The new binary negotiates its own declared versions against these and
    /// the whole N-1 matrix must link.
    pub declared_surface_versions: Vec<(&'static str, u16)>,
    /// The trust artifact the prior binary minted, captured with the store's
    /// genesis identity so the new binary can rebuild the store and re-verify.
    pub trust: CapturedTrust,
}

/// A snapshot of a [`pillar_streamdb::ContentStore`]'s locally-held segments,
/// exposed as a [`SegmentSource`] for the rehydrating new binary.
pub struct SegmentStore {
    entries: std::collections::HashMap<Cid, SignedSegment>,
    /// The owner's signing key pair, captured so a corrupted fixture can be
    /// produced by RE-AUTHORING a segment over mutated bytes (a real signed
    /// segment whose bytes no longer hash to the Cid the head points at — the
    /// content-address integrity break the new binary must reject).
    owner_pub: SigningPublicKey,
    owner_secret: SigningSecretKey,
}

impl SegmentStore {
    fn capture(
        store: &pillar_streamdb::ContentStore,
        cids: &[Cid],
        owner_pub: SigningPublicKey,
        owner_secret: SigningSecretKey,
    ) -> Self {
        let mut entries = std::collections::HashMap::new();
        for cid in cids {
            if let Some(seg) = store.get_local(cid) {
                entries.insert(cid.clone(), seg);
            }
        }
        SegmentStore {
            entries,
            owner_pub,
            owner_secret,
        }
    }

    /// Corrupt the captured segment named by `cid` by re-authoring a genuinely
    /// signed segment over BYTE-FLIPPED content. The new bytes no longer hash
    /// to `cid`, so a rehydrating reader that content-address-verifies the
    /// fetch rejects it (`StoreError::CidMismatch`) rather than silently
    /// reconverging to a wrong view root. This is the deliberately-corrupted
    /// fixture the gate's negative path proves fails closed.
    #[must_use]
    pub fn with_corrupted_segment(mut self, cid: &Cid) -> Self {
        if let Some(seg) = self.entries.get(cid).cloned() {
            let mut bytes = seg.bytes().to_vec();
            if let Some(b) = bytes.last_mut() {
                *b ^= 0xFF;
            } else {
                bytes.push(0xFF);
            }
            let tampered = SignedSegment::author(
                bytes,
                self.owner_pub.clone(),
                &self.owner_secret,
                Visibility::Public,
            )
            .expect("re-author tampered segment");
            self.entries.insert(cid.clone(), tampered);
        }
        self
    }
}

impl SegmentSource for SegmentStore {
    fn fetch(&self, cid: &Cid) -> Option<SignedSegment> {
        self.entries.get(cid).cloned()
    }
}

impl CapturedCellState {
    /// The backfill substrate a rehydrating new binary reads from.
    #[must_use]
    pub fn segment_source(&self) -> &SegmentStore {
        &self.segments
    }

    /// Produce a copy of this capture whose durable stream segments are
    /// CORRUPTED — the deliberately-broken fixture the gate's negative path
    /// asserts the new binary rejects (never silently accepts).
    #[must_use]
    pub fn corrupt_stream_segments(mut self) -> Self {
        let cids: Vec<Cid> = self.segments.entries.keys().cloned().collect();
        for cid in &cids {
            self.segments = self.segments.with_corrupted_segment(cid);
        }
        self
    }
}

/// The real user identity the prior binary enrolled into the scratch cell.
pub struct CapturedUser {
    /// The cold root the op key is enrolled under.
    pub cold_root: String,
    /// The operational key that grants the device.
    pub op_key: String,
    /// The device that logs in.
    pub device: String,
}

/// The trust artifact + genesis identity the prior binary produced.
pub struct CapturedTrust {
    /// The trust store's genesis identity.
    pub genesis: String,
    /// The attestation's issuer identity.
    pub issuer: String,
    /// The subject the capacity is attested to.
    pub subject: String,
    /// The attested role name.
    pub role: String,
    /// The scope the role is bound to.
    pub scope: String,
    /// The predicate action.
    pub action: String,
    /// The predicate resource pattern.
    pub resource: String,
}

pub mod prior_version;
