//! libp2p transport substrate for Pillar.
//!
//! This crate wires together the pieces of the P2 "libp2p substrate" milestone:
//!
//! - [`gossipsub`] for the append-only event log (pub/sub broadcast).
//! - Kademlia (`kad`) for peer discovery / bootstrap.
//! - `relay` + `dcutr` for NAT traversal: a relayed connection first, then an
//!   attempted direct connection upgrade through hole punching.
//!
//! Tor/onion routing is deliberately out of scope here: it is an optional
//! overlay transport, not part of the core substrate.
//!
//! The `*Event` enums below are generated by `#[derive(NetworkBehaviour)]`
//! and cannot themselves carry doc comments on their variants.
#![allow(missing_docs)]
//!
//! The crate exposes two swarm flavours:
//!
//! - [`build_event_swarm`] — a "normal" node behaviour (gossipsub + kademlia +
//!   identify) over TCP and QUIC. Used by nodes that are directly reachable.
//! - [`build_relay_server_swarm`] / [`build_relay_client_swarm`] — a relay
//!   server and the relay-aware client behaviour (gossipsub + kademlia +
//!   identify + relay client + dcutr) used by nodes that need a relay to be
//!   reached (e.g. because they are behind a NAT).

use libp2p::{
    dcutr, gossipsub, identify, identity::Keypair, kad, noise, relay,
    swarm::behaviour::toggle::Toggle, tcp, upnp, yamux, PeerId, Swarm,
};

pub mod blob;
pub use blob::{
    build_blob_swarm, BlobBehaviour, BlobBehaviourEvent, BlobDigest, BlobRequest, BlobResponse,
    BlobStore, BLOB_PROTOCOL_NAME,
};

pub mod antientropy;
pub use antientropy::{
    answer_sync, apply_sync, build_anti_entropy_swarm, AntiEntropyBehaviour,
    AntiEntropyBehaviourEvent, SyncRequest, SyncResponse, ANTI_ENTROPY_PROTOCOL_NAME,
};

/// Gossipsub topic carrying Pillar's append-only event log.
pub const EVENT_LOG_TOPIC: &str = "/pillar/event-log/1.0.0";

/// Protocol name used for the Kademlia DHT instance run by Pillar nodes.
pub const KAD_PROTOCOL_NAME: &str = "/pillar/kad/1.0.0";

/// Returns the [`gossipsub::IdentTopic`] used for Pillar's event log.
pub fn event_log_topic() -> gossipsub::IdentTopic {
    gossipsub::IdentTopic::new(EVENT_LOG_TOPIC)
}

fn kad_config() -> kad::Config {
    kad::Config::new(
        libp2p::StreamProtocol::try_from_owned(KAD_PROTOCOL_NAME.to_string())
            .expect("static protocol name is valid"),
    )
}

fn new_kademlia(peer_id: PeerId) -> kad::Behaviour<kad::store::MemoryStore> {
    let mut kademlia =
        kad::Behaviour::with_config(peer_id, kad::store::MemoryStore::new(peer_id), kad_config());
    // Serve DHT queries from other peers, not just issue our own: without
    // this every node defaults to `Mode::Client` and silently refuses
    // inbound FIND_NODE requests, which makes discovery of a peer that is
    // only reachable through another node's routing table impossible.
    kademlia.set_mode(Some(kad::Mode::Server));
    kademlia
}

fn gossipsub_config() -> gossipsub::Config {
    gossipsub::ConfigBuilder::default()
        .validation_mode(gossipsub::ValidationMode::Strict)
        .build()
        .expect("static gossipsub config is valid")
}

fn gossipsub_behaviour(keypair: &Keypair) -> gossipsub::Behaviour {
    gossipsub::Behaviour::new(
        gossipsub::MessageAuthenticity::Signed(keypair.clone()),
        gossipsub_config(),
    )
    .expect("static gossipsub config is valid")
}

/// The behaviour run by a normal, directly-dialable Pillar node: gossipsub
/// event log, Kademlia discovery, and identify (so peers learn our
/// listen/observed addresses, which Kademlia needs to be useful).
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct EventBehaviour {
    /// Append-only event log broadcast.
    pub gossipsub: gossipsub::Behaviour,
    /// Peer discovery / bootstrap DHT.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange, required for Kademlia to learn dialable
    /// addresses of peers it hears about.
    pub identify: identify::Behaviour,
}

/// The behaviour run by a Pillar node acting as a relay (`libp2p::relay`
/// server side) for other nodes that cannot be dialed directly.
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct RelayServerBehaviour {
    /// Relays circuit-relay-v2 connections for other peers.
    pub relay: relay::Behaviour,
    /// Peer discovery / bootstrap DHT (relays participate in discovery too).
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange.
    pub identify: identify::Behaviour,
}

/// The behaviour run by a Pillar node that may need a relay to be reached
/// (e.g. because it sits behind a NAT): gossipsub + kademlia + identify, plus
/// the relay client and DCUtR (direct connection upgrade through relay) so a
/// relayed connection is upgraded to a direct hole-punched one whenever
/// possible.
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct RelayClientBehaviour {
    /// Append-only event log broadcast.
    pub gossipsub: gossipsub::Behaviour,
    /// Peer discovery / bootstrap DHT.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange.
    pub identify: identify::Behaviour,
    /// Relay client: lets us reserve a slot on a relay and dial/be-dialed
    /// through it via circuit-relay-v2.
    pub relay_client: relay::client::Behaviour,
    /// Direct connection upgrade through relay: attempts to upgrade a
    /// relayed connection to a direct (hole-punched) one.
    pub dcutr: dcutr::Behaviour,
}

fn identify_config(keypair: &Keypair) -> identify::Config {
    identify::Config::new("/pillar/id/1.0.0".to_string(), keypair.public())
}

/// Builds a [`Swarm`] running [`EventBehaviour`] (gossipsub + kademlia +
/// identify) over TCP and QUIC transports, using a freshly generated
/// identity.
pub fn build_event_swarm(
    keypair: Keypair,
) -> Result<Swarm<EventBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_quic()
        .with_behaviour(|key| {
            let peer_id = key.public().to_peer_id();
            EventBehaviour {
                gossipsub: gossipsub_behaviour(key),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
            }
        })?
        .build();
    Ok(swarm)
}

/// Builds a [`Swarm`] running [`RelayServerBehaviour`] over TCP, acting as a
/// circuit-relay-v2 relay for other Pillar nodes.
pub fn build_relay_server_swarm(
    keypair: Keypair,
) -> Result<Swarm<RelayServerBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_behaviour(|key| {
            let peer_id = key.public().to_peer_id();
            RelayServerBehaviour {
                relay: relay::Behaviour::new(peer_id, relay::Config::default()),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
            }
        })?
        .build();
    Ok(swarm)
}

/// Builds a [`Swarm`] running [`RelayClientBehaviour`] over TCP, with the
/// relay-client transport wired in so it can reserve a slot on / dial through
/// a relay and attempt DCUtR hole punching.
pub fn build_relay_client_swarm(
    keypair: Keypair,
) -> Result<Swarm<RelayClientBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_relay_client(noise::Config::new, yamux::Config::default)?
        .with_behaviour(|key, relay_client| {
            let peer_id = key.public().to_peer_id();
            RelayClientBehaviour {
                gossipsub: gossipsub_behaviour(key),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
                relay_client,
                dcutr: dcutr::Behaviour::new(peer_id),
            }
        })?
        .build();
    Ok(swarm)
}

/// Convenience: the [`PeerId`] a [`Keypair`] resolves to.
pub fn peer_id_of(keypair: &Keypair) -> PeerId {
    keypair.public().to_peer_id()
}

/// Optional decentralized overlay mesh: reliability resources (liveness), not
/// safety.
///
/// **INVARIANT**: the overlay is strictly additive on top of [`EventBehaviour`]
/// / [`RelayClientBehaviour`] / [`RelayServerBehaviour`] and must NEVER become
/// a bootstrap dependency of the substrate. Concretely: [`build_event_swarm`]
/// and friends never reference this module, and [`build_overlay_event_swarm`]
/// with `overlay_enabled: false` degrades to exactly the plain substrate
/// behaviour (see `substrate_bootstraps_with_overlay_disabled` in the tests
/// below). The overlay's own peer-mesh metadata (addresses/capabilities a
/// node advertises to the mesh) is NOT pushed over its own bespoke gossip
/// channel; it rides the existing streaming DB (`pillar_streamdb`) as
/// ordinary content-addressed ops, per the ROI's "metadata rides the
/// streaming DB" requirement — see [`MeshPeerRecord::encode`] /
/// [`MeshPeerRecord::decode`], which are the pure (de)serialization the
/// `pillar-streamdb` round-trip test in this crate's dev-dependencies drives
/// an [`pillar_streamdb`]-backed `Op` payload through.
pub mod overlay {
    use libp2p::{multiaddr::Multiaddr, PeerId};
    use std::str::FromStr;

    /// A mesh peer's advertised reachability: its [`PeerId`] plus every
    /// [`Multiaddr`] it wants the overlay to know about (its role in the
    /// decentralized headscale/Nebula-analog overlay).
    ///
    /// This is pure metadata with no network behaviour of its own — it is
    /// produced/consumed by whatever already-connected substrate transport
    /// (gossipsub, direct RPC, …) a node uses to publish to its stream; the
    /// overlay never needs its own bootstrap channel to exchange it.
    #[derive(Clone, Debug, PartialEq, Eq)]
    pub struct MeshPeerRecord {
        peer_id: PeerId,
        addresses: Vec<Multiaddr>,
    }

    impl MeshPeerRecord {
        /// Build a record for `peer_id` advertising `addresses`.
        #[must_use]
        pub fn new(peer_id: PeerId, addresses: Vec<Multiaddr>) -> Self {
            MeshPeerRecord { peer_id, addresses }
        }

        /// This record's [`PeerId`].
        #[must_use]
        pub fn peer_id(&self) -> PeerId {
            self.peer_id
        }

        /// The addresses this record advertises.
        #[must_use]
        pub fn addresses(&self) -> &[Multiaddr] {
            &self.addresses
        }

        /// Encode this record to bytes suitable as a `pillar_streamdb::Op`
        /// payload: a simple length-prefixed, dependency-free wire format
        /// (newline-delimited UTF-8 strings — the peer id then each
        /// multiaddr), so the metadata can ride any content-addressed op
        /// log without requiring `pillar-streamdb` (or any serde crate) as a
        /// runtime dependency of this crate.
        #[must_use]
        pub fn encode(&self) -> Vec<u8> {
            let mut lines = vec![self.peer_id.to_base58()];
            lines.extend(self.addresses.iter().map(std::string::ToString::to_string));
            lines.join("\n").into_bytes()
        }

        /// Decode a record previously produced by [`Self::encode`].
        ///
        /// # Errors
        ///
        /// Returns [`DecodeError`] if `bytes` is not valid UTF-8, is empty, or
        /// its first line is not a valid [`PeerId`], or any subsequent line is
        /// not a valid [`Multiaddr`].
        pub fn decode(bytes: &[u8]) -> Result<Self, DecodeError> {
            let text = std::str::from_utf8(bytes).map_err(|_| DecodeError::NotUtf8)?;
            let mut lines = text.lines();
            let peer_id_line = lines.next().ok_or(DecodeError::Empty)?;
            let peer_id = PeerId::from_str(peer_id_line).map_err(|_| DecodeError::InvalidPeerId)?;
            let addresses = lines
                .map(|line| Multiaddr::from_str(line).map_err(|_| DecodeError::InvalidAddress))
                .collect::<Result<Vec<_>, _>>()?;
            Ok(MeshPeerRecord { peer_id, addresses })
        }
    }

    /// A [`MeshPeerRecord::decode`] failure.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum DecodeError {
        /// The payload was not valid UTF-8.
        NotUtf8,
        /// The payload was empty (no peer id line).
        Empty,
        /// The first line was not a valid [`PeerId`].
        InvalidPeerId,
        /// A subsequent line was not a valid [`Multiaddr`].
        InvalidAddress,
    }

    impl std::fmt::Display for DecodeError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            let msg = match self {
                DecodeError::NotUtf8 => "mesh peer record payload was not valid UTF-8",
                DecodeError::Empty => "mesh peer record payload was empty",
                DecodeError::InvalidPeerId => {
                    "mesh peer record's first line was not a valid PeerId"
                }
                DecodeError::InvalidAddress => "mesh peer record contained an invalid Multiaddr",
            };
            f.write_str(msg)
        }
    }

    impl std::error::Error for DecodeError {}
}

/// The behaviour run by a normal Pillar node with the OPTIONAL overlay mesh
/// enabled: exactly [`EventBehaviour`] (gossipsub event log, Kademlia
/// discovery, identify) plus a [`Toggle`]d UPnP/NAT-PMP behaviour that tries
/// to open a port mapping on the local gateway to reduce partition
/// frequency/duration.
///
/// The `upnp` field is a [`Toggle`], not a bare [`upnp::tokio::Behaviour`],
/// specifically so the overlay can be compiled in but runtime-disabled
/// without changing the behaviour type — this is what lets
/// [`build_overlay_event_swarm`] guarantee the substrate boots identically
/// whether or not the overlay is present.
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct OverlayEventBehaviour {
    /// Append-only event log broadcast.
    pub gossipsub: gossipsub::Behaviour,
    /// Peer discovery / bootstrap DHT.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange.
    pub identify: identify::Behaviour,
    /// Optional UPnP/NAT-PMP port mapping — the overlay's reliability
    /// resource. Disabled (`Toggle::from(None)`) leaves this behaviour
    /// entirely inert, at which point [`OverlayEventBehaviour`] behaves
    /// exactly like [`EventBehaviour`].
    pub upnp: Toggle<upnp::tokio::Behaviour>,
}

/// Builds a [`Swarm`] running [`OverlayEventBehaviour`]: the same substrate
/// as [`build_event_swarm`] (gossipsub + kademlia + identify) with the
/// optional overlay mesh's UPnP/NAT-PMP port mapping toggled by
/// `overlay_enabled`.
///
/// **INVARIANT**: with `overlay_enabled: false` this is behaviourally
/// identical to [`build_event_swarm`] — the substrate never requires the
/// overlay to bootstrap. See `substrate_bootstraps_with_overlay_disabled`.
pub fn build_overlay_event_swarm(
    keypair: Keypair,
    overlay_enabled: bool,
) -> Result<Swarm<OverlayEventBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_quic()
        .with_behaviour(|key| {
            let peer_id = key.public().to_peer_id();
            let upnp = if overlay_enabled {
                Toggle::from(Some(upnp::tokio::Behaviour::default()))
            } else {
                Toggle::from(None)
            };
            OverlayEventBehaviour {
                gossipsub: gossipsub_behaviour(key),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
                upnp,
            }
        })?
        .build();
    Ok(swarm)
}

#[cfg(test)]
mod tests {
    use super::*;
    use futures::StreamExt;
    use libp2p::core::multiaddr::{Multiaddr, Protocol};
    use libp2p::swarm::SwarmEvent;
    use std::time::Duration;
    use tokio::time::timeout;

    fn local_tcp_listen_addr() -> Multiaddr {
        Multiaddr::empty()
            .with(Protocol::Ip4(std::net::Ipv4Addr::LOCALHOST))
            .with(Protocol::Tcp(0))
    }

    /// Drives `swarm` until `pred` returns `Some`, or the overall deadline
    /// elapses (in which case the test fails via `expect`).
    async fn drive_until<B: libp2p::swarm::NetworkBehaviour, T>(
        swarm: &mut Swarm<B>,
        deadline: Duration,
        mut pred: impl FnMut(&SwarmEvent<B::ToSwarm>) -> Option<T>,
    ) -> T {
        timeout(deadline, async {
            loop {
                let event = swarm.select_next_some().await;
                if let Some(v) = pred(&event) {
                    return v;
                }
            }
        })
        .await
        .expect("deadline elapsed waiting for expected swarm event")
    }

    async fn listen_and_get_addr<B: libp2p::swarm::NetworkBehaviour>(
        swarm: &mut Swarm<B>,
    ) -> Multiaddr {
        swarm.listen_on(local_tcp_listen_addr()).unwrap();
        drive_until(swarm, Duration::from_secs(10), |event| match event {
            SwarmEvent::NewListenAddr { address, .. } => Some(address.clone()),
            _ => None,
        })
        .await
    }

    /// Local multi-node swarm delivery: two [`EventBehaviour`] nodes connect
    /// directly, both subscribe to the event-log topic, and a message
    /// published by one is received by the other.
    #[tokio::test]
    async fn gossipsub_delivers_across_local_swarm() {
        let mut a = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let mut b = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let b_peer_id = *b.local_peer_id();

        let topic = event_log_topic();
        a.behaviour_mut().gossipsub.subscribe(&topic).unwrap();
        b.behaviour_mut().gossipsub.subscribe(&topic).unwrap();

        let b_addr = listen_and_get_addr(&mut b).await;
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        // Drive both swarms until gossipsub reports mesh subscription on both
        // sides (needed before publish reliably propagates over a mesh of
        // size 1) then publish and assert delivery.
        let deadline = Duration::from_secs(20);
        let drive_a = async {
            loop {
                if let SwarmEvent::Behaviour(EventBehaviourEvent::Gossipsub(
                    gossipsub::Event::Subscribed { .. },
                )) = a.select_next_some().await
                {
                    break;
                }
            }
        };
        let drive_b = async {
            loop {
                if let SwarmEvent::Behaviour(EventBehaviourEvent::Gossipsub(
                    gossipsub::Event::Subscribed { .. },
                )) = b.select_next_some().await
                {
                    break;
                }
            }
        };
        timeout(deadline, futures::future::join(drive_a, drive_b))
            .await
            .expect("both peers subscribed to the topic");

        a.behaviour_mut()
            .gossipsub
            .publish(topic.clone(), b"hello-pillar-event-log".to_vec())
            .expect("publish succeeds once mesh formed");

        let received = drive_until(&mut b, deadline, |event| match event {
            SwarmEvent::Behaviour(EventBehaviourEvent::Gossipsub(gossipsub::Event::Message {
                message,
                ..
            })) => Some(message.data.clone()),
            _ => None,
        })
        .await;
        assert_eq!(received, b"hello-pillar-event-log");
    }

    /// Kademlia discovery: two [`EventBehaviour`] nodes are bootstrapped
    /// against each other by address, and a `get_closest_peers` query from
    /// one successfully returns the other.
    #[tokio::test]
    async fn kademlia_discovers_peer() {
        let mut a = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let mut b = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let b_peer_id = *b.local_peer_id();

        let b_addr = listen_and_get_addr(&mut b).await;
        a.behaviour_mut()
            .kademlia
            .add_address(&b_peer_id, b_addr.clone());
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        // Keep `b` being polled in the background for the rest of the test
        // so it can accept the connection and answer `a`'s query.
        tokio::spawn(async move {
            loop {
                b.select_next_some().await;
            }
        });

        // Wait for the connection so the routing table entry is dialable.
        drive_until(&mut a, Duration::from_secs(10), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == b_peer_id => Some(()),
            _ => None,
        })
        .await;

        let query_id = a.behaviour_mut().kademlia.get_closest_peers(b_peer_id);

        let found = drive_until(&mut a, Duration::from_secs(15), |event| match event {
            SwarmEvent::Behaviour(EventBehaviourEvent::Kademlia(
                kad::Event::OutboundQueryProgressed {
                    id,
                    result: kad::QueryResult::GetClosestPeers(Ok(result)),
                    step,
                    ..
                },
            )) if *id == query_id && step.last => {
                Some(result.peers.iter().any(|p| p.peer_id == b_peer_id))
            }
            _ => None,
        })
        .await;
        assert!(
            found,
            "kademlia get_closest_peers should discover the bootstrapped peer"
        );
    }

    /// Relayed dial: a relay server node, plus two relay-client nodes `a`
    /// (the "reachable-only-via-relay" node) and `b` (the dialer). `a`
    /// listens through the relay's circuit-relay-v2 address; `b` dials `a`
    /// exclusively via that relayed address and the connection is
    /// established.
    #[tokio::test]
    async fn relayed_dial_succeeds() {
        let _ = tracing_subscriber::fmt()
            .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
            .try_init();
        let mut relay_swarm = build_relay_server_swarm(Keypair::generate_ed25519()).unwrap();
        let relay_peer_id = *relay_swarm.local_peer_id();
        let relay_addr = listen_and_get_addr(&mut relay_swarm).await;
        // The relay needs its own external address to include in reservation
        // responses, or it refuses reservations with `NoAddressesInReservation`.
        relay_swarm.add_external_address(relay_addr.clone());

        let mut a = build_relay_client_swarm(Keypair::generate_ed25519()).unwrap();
        let a_peer_id = *a.local_peer_id();
        let mut b = build_relay_client_swarm(Keypair::generate_ed25519()).unwrap();

        // `a` needs at least one (fake, for this loopback test) external
        // address to include in its relay reservation request, or the relay
        // refuses the reservation with `NoAddressesInReservation`.
        let a_tcp_addr = listen_and_get_addr(&mut a).await;
        a.add_external_address(a_tcp_addr);

        // Drive the relay server in the background for the whole test.
        tokio::spawn(async move {
            loop {
                relay_swarm.select_next_some().await;
            }
        });

        // `a` dials the relay directly, then listens on the relayed address
        // (reserving a slot on the relay for circuit-relay-v2).
        a.dial(relay_addr.clone().with(Protocol::P2p(relay_peer_id)))
            .unwrap();
        drive_until(&mut a, Duration::from_secs(10), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == relay_peer_id => {
                Some(())
            }
            _ => None,
        })
        .await;

        let relayed_listen_addr = relay_addr
            .clone()
            .with(Protocol::P2p(relay_peer_id))
            .with(Protocol::P2pCircuit);
        a.listen_on(relayed_listen_addr.clone()).unwrap();

        // Drive `a` until the relay confirms the reservation.
        let drive_a_reservation = async {
            loop {
                if let SwarmEvent::Behaviour(RelayClientBehaviourEvent::RelayClient(
                    relay::client::Event::ReservationReqAccepted { .. },
                )) = a.select_next_some().await
                {
                    break;
                }
            }
        };
        timeout(Duration::from_secs(10), drive_a_reservation)
            .await
            .expect("relay reservation accepted");

        // Keep driving `a` in the background so it can answer the incoming
        // relayed dial from `b`.
        tokio::spawn(async move {
            loop {
                a.select_next_some().await;
            }
        });

        // `b` dials `a` purely through the relay circuit address.
        let dial_addr = relay_addr
            .with(Protocol::P2p(relay_peer_id))
            .with(Protocol::P2pCircuit)
            .with(Protocol::P2p(a_peer_id));
        b.dial(dial_addr).unwrap();

        drive_until(&mut b, Duration::from_secs(20), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == a_peer_id => Some(()),
            _ => None,
        })
        .await;
    }

    /// INVARIANT under test: the overlay mesh must never be a bootstrap
    /// dependency of the substrate. A node built with
    /// `build_overlay_event_swarm(.., overlay_enabled: false)` must still
    /// bootstrap and run the same substrate protocols (gossipsub, kademlia)
    /// as plain [`build_event_swarm`] — with the overlay's UPnP behaviour
    /// entirely absent, not merely idle.
    #[tokio::test]
    async fn substrate_bootstraps_with_overlay_disabled() {
        let mut a = build_overlay_event_swarm(Keypair::generate_ed25519(), false).unwrap();
        let mut b = build_overlay_event_swarm(Keypair::generate_ed25519(), false).unwrap();
        let b_peer_id = *b.local_peer_id();

        // The overlay behaviour is disabled: no gateway search task is
        // spawned, so there is nothing overlay-related to wait on. Bootstrap
        // proceeds purely on the substrate (kademlia + identify), exactly as
        // it does for `build_event_swarm`.
        let b_addr = listen_and_get_addr(&mut b).await;
        a.behaviour_mut()
            .kademlia
            .add_address(&b_peer_id, b_addr.clone());
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        tokio::spawn(async move {
            loop {
                b.select_next_some().await;
            }
        });

        drive_until(&mut a, Duration::from_secs(10), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == b_peer_id => Some(()),
            _ => None,
        })
        .await;

        let query_id = a.behaviour_mut().kademlia.get_closest_peers(b_peer_id);
        let found = drive_until(&mut a, Duration::from_secs(15), |event| match event {
            SwarmEvent::Behaviour(OverlayEventBehaviourEvent::Kademlia(
                kad::Event::OutboundQueryProgressed {
                    id,
                    result: kad::QueryResult::GetClosestPeers(Ok(result)),
                    step,
                    ..
                },
            )) if *id == query_id && step.last => {
                Some(result.peers.iter().any(|p| p.peer_id == b_peer_id))
            }
            _ => None,
        })
        .await;
        assert!(
            found,
            "substrate (kademlia) must bootstrap fully with the overlay disabled"
        );
    }

    /// Mesh metadata round-trips through the streaming DB: a
    /// [`overlay::MeshPeerRecord`] survives `encode` -> [`pillar_streamdb::Op`]
    /// append -> gossip/merge into another node's log -> read back -> `decode`,
    /// unchanged. This is the "metadata rides the streaming DB" requirement:
    /// the overlay never gets its own bespoke metadata-gossip channel.
    #[test]
    fn mesh_metadata_round_trips_via_streaming_db() {
        use overlay::MeshPeerRecord;
        use pillar_streamdb::OpLog;

        let peer_id = PeerId::random();
        let addr_a: Multiaddr = "/ip4/127.0.0.1/tcp/4001".parse().unwrap();
        let addr_b: Multiaddr = "/ip4/198.51.100.7/udp/4002/quic-v1".parse().unwrap();
        let record = MeshPeerRecord::new(peer_id, vec![addr_a, addr_b]);

        // The node holding the record appends it to its stream (its slice of
        // the shared content-addressed op log).
        let mut publisher_log = OpLog::new();
        let op_id = publisher_log.append(record.encode());

        // Gossiped to another node exactly like any other op — pure CRDT
        // merge, no overlay-specific transport involved.
        let mut receiver_log = OpLog::new();
        receiver_log.merge(&publisher_log);
        assert!(receiver_log.contains(op_id));

        // The receiver reads the op back out of its materialized order and
        // decodes it to the identical mesh peer record.
        let stored_op = receiver_log
            .order()
            .into_iter()
            .find(|op| op.id() == op_id)
            .expect("appended op is present in the materialized order");
        let decoded = MeshPeerRecord::decode(stored_op.payload())
            .expect("a record encoded by MeshPeerRecord::encode always decodes");
        assert_eq!(decoded, record);
    }
}
