//! libp2p transport substrate for Pillar.
//!
//! This crate wires together the pieces of the P2 "libp2p substrate" milestone:
//!
//! - [`gossipsub`] for the append-only event log (pub/sub broadcast).
//! - Kademlia (`kad`) for peer discovery / bootstrap.
//! - `relay` + `dcutr` for NAT traversal: a relayed connection first, then an
//!   attempted direct connection upgrade through hole punching.
//!
//! Tor/onion routing is deliberately out of scope here: it is an optional
//! overlay transport, not part of the core substrate.
//!
//! The `*Event` enums below are generated by `#[derive(NetworkBehaviour)]`
//! and cannot themselves carry doc comments on their variants.
#![allow(missing_docs)]
//!
//! The crate exposes two swarm flavours:
//!
//! - [`build_event_swarm`] — a "normal" node behaviour (gossipsub + kademlia +
//!   identify) over TCP and QUIC. Used by nodes that are directly reachable.
//! - [`build_relay_server_swarm`] / [`build_relay_client_swarm`] — a relay
//!   server and the relay-aware client behaviour (gossipsub + kademlia +
//!   identify + relay client + dcutr) used by nodes that need a relay to be
//!   reached (e.g. because they are behind a NAT).

use libp2p::{
    dcutr, gossipsub, identify, identity::Keypair, kad, noise, relay, tcp, yamux, PeerId, Swarm,
};

pub mod blob;
pub use blob::{
    build_blob_swarm, BlobBehaviour, BlobBehaviourEvent, BlobDigest, BlobRequest, BlobResponse,
    BlobStore, BLOB_PROTOCOL_NAME,
};

/// Gossipsub topic carrying Pillar's append-only event log.
pub const EVENT_LOG_TOPIC: &str = "/pillar/event-log/1.0.0";

/// Protocol name used for the Kademlia DHT instance run by Pillar nodes.
pub const KAD_PROTOCOL_NAME: &str = "/pillar/kad/1.0.0";

/// Returns the [`gossipsub::IdentTopic`] used for Pillar's event log.
pub fn event_log_topic() -> gossipsub::IdentTopic {
    gossipsub::IdentTopic::new(EVENT_LOG_TOPIC)
}

fn kad_config() -> kad::Config {
    kad::Config::new(
        libp2p::StreamProtocol::try_from_owned(KAD_PROTOCOL_NAME.to_string())
            .expect("static protocol name is valid"),
    )
}

fn new_kademlia(peer_id: PeerId) -> kad::Behaviour<kad::store::MemoryStore> {
    let mut kademlia =
        kad::Behaviour::with_config(peer_id, kad::store::MemoryStore::new(peer_id), kad_config());
    // Serve DHT queries from other peers, not just issue our own: without
    // this every node defaults to `Mode::Client` and silently refuses
    // inbound FIND_NODE requests, which makes discovery of a peer that is
    // only reachable through another node's routing table impossible.
    kademlia.set_mode(Some(kad::Mode::Server));
    kademlia
}

fn gossipsub_config() -> gossipsub::Config {
    gossipsub::ConfigBuilder::default()
        .validation_mode(gossipsub::ValidationMode::Strict)
        .build()
        .expect("static gossipsub config is valid")
}

fn gossipsub_behaviour(keypair: &Keypair) -> gossipsub::Behaviour {
    gossipsub::Behaviour::new(
        gossipsub::MessageAuthenticity::Signed(keypair.clone()),
        gossipsub_config(),
    )
    .expect("static gossipsub config is valid")
}

/// The behaviour run by a normal, directly-dialable Pillar node: gossipsub
/// event log, Kademlia discovery, and identify (so peers learn our
/// listen/observed addresses, which Kademlia needs to be useful).
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct EventBehaviour {
    /// Append-only event log broadcast.
    pub gossipsub: gossipsub::Behaviour,
    /// Peer discovery / bootstrap DHT.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange, required for Kademlia to learn dialable
    /// addresses of peers it hears about.
    pub identify: identify::Behaviour,
}

/// The behaviour run by a Pillar node acting as a relay (`libp2p::relay`
/// server side) for other nodes that cannot be dialed directly.
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct RelayServerBehaviour {
    /// Relays circuit-relay-v2 connections for other peers.
    pub relay: relay::Behaviour,
    /// Peer discovery / bootstrap DHT (relays participate in discovery too).
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange.
    pub identify: identify::Behaviour,
}

/// The behaviour run by a Pillar node that may need a relay to be reached
/// (e.g. because it sits behind a NAT): gossipsub + kademlia + identify, plus
/// the relay client and DCUtR (direct connection upgrade through relay) so a
/// relayed connection is upgraded to a direct hole-punched one whenever
/// possible.
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct RelayClientBehaviour {
    /// Append-only event log broadcast.
    pub gossipsub: gossipsub::Behaviour,
    /// Peer discovery / bootstrap DHT.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange.
    pub identify: identify::Behaviour,
    /// Relay client: lets us reserve a slot on a relay and dial/be-dialed
    /// through it via circuit-relay-v2.
    pub relay_client: relay::client::Behaviour,
    /// Direct connection upgrade through relay: attempts to upgrade a
    /// relayed connection to a direct (hole-punched) one.
    pub dcutr: dcutr::Behaviour,
}

fn identify_config(keypair: &Keypair) -> identify::Config {
    identify::Config::new("/pillar/id/1.0.0".to_string(), keypair.public())
}

/// Builds a [`Swarm`] running [`EventBehaviour`] (gossipsub + kademlia +
/// identify) over TCP and QUIC transports, using a freshly generated
/// identity.
pub fn build_event_swarm(
    keypair: Keypair,
) -> Result<Swarm<EventBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_quic()
        .with_behaviour(|key| {
            let peer_id = key.public().to_peer_id();
            EventBehaviour {
                gossipsub: gossipsub_behaviour(key),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
            }
        })?
        .build();
    Ok(swarm)
}

/// Builds a [`Swarm`] running [`RelayServerBehaviour`] over TCP, acting as a
/// circuit-relay-v2 relay for other Pillar nodes.
pub fn build_relay_server_swarm(
    keypair: Keypair,
) -> Result<Swarm<RelayServerBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_behaviour(|key| {
            let peer_id = key.public().to_peer_id();
            RelayServerBehaviour {
                relay: relay::Behaviour::new(peer_id, relay::Config::default()),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
            }
        })?
        .build();
    Ok(swarm)
}

/// Builds a [`Swarm`] running [`RelayClientBehaviour`] over TCP, with the
/// relay-client transport wired in so it can reserve a slot on / dial through
/// a relay and attempt DCUtR hole punching.
pub fn build_relay_client_swarm(
    keypair: Keypair,
) -> Result<Swarm<RelayClientBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_relay_client(noise::Config::new, yamux::Config::default)?
        .with_behaviour(|key, relay_client| {
            let peer_id = key.public().to_peer_id();
            RelayClientBehaviour {
                gossipsub: gossipsub_behaviour(key),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
                relay_client,
                dcutr: dcutr::Behaviour::new(peer_id),
            }
        })?
        .build();
    Ok(swarm)
}

/// Convenience: the [`PeerId`] a [`Keypair`] resolves to.
pub fn peer_id_of(keypair: &Keypair) -> PeerId {
    keypair.public().to_peer_id()
}

#[cfg(test)]
mod tests {
    use super::*;
    use futures::StreamExt;
    use libp2p::core::multiaddr::{Multiaddr, Protocol};
    use libp2p::swarm::SwarmEvent;
    use std::time::Duration;
    use tokio::time::timeout;

    fn local_tcp_listen_addr() -> Multiaddr {
        Multiaddr::empty()
            .with(Protocol::Ip4(std::net::Ipv4Addr::LOCALHOST))
            .with(Protocol::Tcp(0))
    }

    /// Drives `swarm` until `pred` returns `Some`, or the overall deadline
    /// elapses (in which case the test fails via `expect`).
    async fn drive_until<B: libp2p::swarm::NetworkBehaviour, T>(
        swarm: &mut Swarm<B>,
        deadline: Duration,
        mut pred: impl FnMut(&SwarmEvent<B::ToSwarm>) -> Option<T>,
    ) -> T {
        timeout(deadline, async {
            loop {
                let event = swarm.select_next_some().await;
                if let Some(v) = pred(&event) {
                    return v;
                }
            }
        })
        .await
        .expect("deadline elapsed waiting for expected swarm event")
    }

    async fn listen_and_get_addr<B: libp2p::swarm::NetworkBehaviour>(
        swarm: &mut Swarm<B>,
    ) -> Multiaddr {
        swarm.listen_on(local_tcp_listen_addr()).unwrap();
        drive_until(swarm, Duration::from_secs(10), |event| match event {
            SwarmEvent::NewListenAddr { address, .. } => Some(address.clone()),
            _ => None,
        })
        .await
    }

    /// Local multi-node swarm delivery: two [`EventBehaviour`] nodes connect
    /// directly, both subscribe to the event-log topic, and a message
    /// published by one is received by the other.
    #[tokio::test]
    async fn gossipsub_delivers_across_local_swarm() {
        let mut a = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let mut b = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let b_peer_id = *b.local_peer_id();

        let topic = event_log_topic();
        a.behaviour_mut().gossipsub.subscribe(&topic).unwrap();
        b.behaviour_mut().gossipsub.subscribe(&topic).unwrap();

        let b_addr = listen_and_get_addr(&mut b).await;
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        // Drive both swarms until gossipsub reports mesh subscription on both
        // sides (needed before publish reliably propagates over a mesh of
        // size 1) then publish and assert delivery.
        let deadline = Duration::from_secs(20);
        let drive_a = async {
            loop {
                if let SwarmEvent::Behaviour(EventBehaviourEvent::Gossipsub(
                    gossipsub::Event::Subscribed { .. },
                )) = a.select_next_some().await
                {
                    break;
                }
            }
        };
        let drive_b = async {
            loop {
                if let SwarmEvent::Behaviour(EventBehaviourEvent::Gossipsub(
                    gossipsub::Event::Subscribed { .. },
                )) = b.select_next_some().await
                {
                    break;
                }
            }
        };
        timeout(deadline, futures::future::join(drive_a, drive_b))
            .await
            .expect("both peers subscribed to the topic");

        a.behaviour_mut()
            .gossipsub
            .publish(topic.clone(), b"hello-pillar-event-log".to_vec())
            .expect("publish succeeds once mesh formed");

        let received = drive_until(&mut b, deadline, |event| match event {
            SwarmEvent::Behaviour(EventBehaviourEvent::Gossipsub(gossipsub::Event::Message {
                message,
                ..
            })) => Some(message.data.clone()),
            _ => None,
        })
        .await;
        assert_eq!(received, b"hello-pillar-event-log");
    }

    /// Kademlia discovery: two [`EventBehaviour`] nodes are bootstrapped
    /// against each other by address, and a `get_closest_peers` query from
    /// one successfully returns the other.
    #[tokio::test]
    async fn kademlia_discovers_peer() {
        let mut a = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let mut b = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let b_peer_id = *b.local_peer_id();

        let b_addr = listen_and_get_addr(&mut b).await;
        a.behaviour_mut()
            .kademlia
            .add_address(&b_peer_id, b_addr.clone());
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        // Keep `b` being polled in the background for the rest of the test
        // so it can accept the connection and answer `a`'s query.
        tokio::spawn(async move {
            loop {
                b.select_next_some().await;
            }
        });

        // Wait for the connection so the routing table entry is dialable.
        drive_until(&mut a, Duration::from_secs(10), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == b_peer_id => Some(()),
            _ => None,
        })
        .await;

        let query_id = a.behaviour_mut().kademlia.get_closest_peers(b_peer_id);

        let found = drive_until(&mut a, Duration::from_secs(15), |event| match event {
            SwarmEvent::Behaviour(EventBehaviourEvent::Kademlia(
                kad::Event::OutboundQueryProgressed {
                    id,
                    result: kad::QueryResult::GetClosestPeers(Ok(result)),
                    step,
                    ..
                },
            )) if *id == query_id && step.last => {
                Some(result.peers.iter().any(|p| p.peer_id == b_peer_id))
            }
            _ => None,
        })
        .await;
        assert!(
            found,
            "kademlia get_closest_peers should discover the bootstrapped peer"
        );
    }

    /// Relayed dial: a relay server node, plus two relay-client nodes `a`
    /// (the "reachable-only-via-relay" node) and `b` (the dialer). `a`
    /// listens through the relay's circuit-relay-v2 address; `b` dials `a`
    /// exclusively via that relayed address and the connection is
    /// established.
    #[tokio::test]
    async fn relayed_dial_succeeds() {
        let _ = tracing_subscriber::fmt()
            .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
            .try_init();
        let mut relay_swarm = build_relay_server_swarm(Keypair::generate_ed25519()).unwrap();
        let relay_peer_id = *relay_swarm.local_peer_id();
        let relay_addr = listen_and_get_addr(&mut relay_swarm).await;
        // The relay needs its own external address to include in reservation
        // responses, or it refuses reservations with `NoAddressesInReservation`.
        relay_swarm.add_external_address(relay_addr.clone());

        let mut a = build_relay_client_swarm(Keypair::generate_ed25519()).unwrap();
        let a_peer_id = *a.local_peer_id();
        let mut b = build_relay_client_swarm(Keypair::generate_ed25519()).unwrap();

        // `a` needs at least one (fake, for this loopback test) external
        // address to include in its relay reservation request, or the relay
        // refuses the reservation with `NoAddressesInReservation`.
        let a_tcp_addr = listen_and_get_addr(&mut a).await;
        a.add_external_address(a_tcp_addr);

        // Drive the relay server in the background for the whole test.
        tokio::spawn(async move {
            loop {
                relay_swarm.select_next_some().await;
            }
        });

        // `a` dials the relay directly, then listens on the relayed address
        // (reserving a slot on the relay for circuit-relay-v2).
        a.dial(relay_addr.clone().with(Protocol::P2p(relay_peer_id)))
            .unwrap();
        drive_until(&mut a, Duration::from_secs(10), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == relay_peer_id => {
                Some(())
            }
            _ => None,
        })
        .await;

        let relayed_listen_addr = relay_addr
            .clone()
            .with(Protocol::P2p(relay_peer_id))
            .with(Protocol::P2pCircuit);
        a.listen_on(relayed_listen_addr.clone()).unwrap();

        // Drive `a` until the relay confirms the reservation.
        let drive_a_reservation = async {
            loop {
                if let SwarmEvent::Behaviour(RelayClientBehaviourEvent::RelayClient(
                    relay::client::Event::ReservationReqAccepted { .. },
                )) = a.select_next_some().await
                {
                    break;
                }
            }
        };
        timeout(Duration::from_secs(10), drive_a_reservation)
            .await
            .expect("relay reservation accepted");

        // Keep driving `a` in the background so it can answer the incoming
        // relayed dial from `b`.
        tokio::spawn(async move {
            loop {
                a.select_next_some().await;
            }
        });

        // `b` dials `a` purely through the relay circuit address.
        let dial_addr = relay_addr
            .with(Protocol::P2p(relay_peer_id))
            .with(Protocol::P2pCircuit)
            .with(Protocol::P2p(a_peer_id));
        b.dial(dial_addr).unwrap();

        drive_until(&mut b, Duration::from_secs(20), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == a_peer_id => Some(()),
            _ => None,
        })
        .await;
    }
}
