//! libp2p transport substrate for Pillar.
//!
//! This crate wires together the pieces of the P2 "libp2p substrate" milestone:
//!
//! - [`gossipsub`] for the append-only event log (pub/sub broadcast).
//! - Kademlia (`kad`) for peer discovery / bootstrap.
//! - `relay` + `dcutr` for NAT traversal: a relayed connection first, then an
//!   attempted direct connection upgrade through hole punching.
//!
//! Tor/onion routing is deliberately out of scope here: it is an optional
//! overlay transport, not part of the core substrate.
//!
//! The `*Event` enums below are generated by `#[derive(NetworkBehaviour)]`
//! and cannot themselves carry doc comments on their variants.
#![allow(missing_docs)]
//!
//! The crate exposes two swarm flavours:
//!
//! - [`build_event_swarm`] — a "normal" node behaviour (gossipsub + kademlia +
//!   identify) over TCP and QUIC. Used by nodes that are directly reachable.
//! - [`build_relay_server_swarm`] / [`build_relay_client_swarm`] — a relay
//!   server and the relay-aware client behaviour (gossipsub + kademlia +
//!   identify + relay client + dcutr) used by nodes that need a relay to be
//!   reached (e.g. because they are behind a NAT).

use libp2p::{
    core::{muxing::StreamMuxerBox, upgrade::Version},
    dcutr, gossipsub, identify,
    identity::Keypair,
    kad, noise,
    pnet::{PnetConfig, PreSharedKey},
    relay,
    swarm::behaviour::toggle::Toggle,
    tcp, upnp, yamux, PeerId, Swarm, Transport,
};

pub mod pillar_udp;

pub mod udp_dataplane;
pub use udp_dataplane::{UdpDataplane, HEALTH_PROBE};

pub mod pillar_udp_transport;
pub use pillar_udp_transport::{
    is_pillar_udp_addr, pillar_udp_multiaddr, pillar_udp_socket_addr, PillarUdpStream,
    PillarUdpTransport, PILLAR_UDP_SUFFIX,
};

pub mod blob;
pub use blob::{
    build_blob_swarm, BlobBehaviour, BlobBehaviourEvent, BlobDigest, BlobRequest, BlobResponse,
    BlobStore, BLOB_PROTOCOL_NAME,
};

pub mod antientropy;
pub use antientropy::{
    answer_sync, apply_sync, build_anti_entropy_swarm, AntiEntropyBehaviour,
    AntiEntropyBehaviourEvent, SyncRequest, SyncResponse, ANTI_ENTROPY_PROTOCOL_NAME,
};

/// Gossipsub topic carrying Pillar's append-only event log.
pub const EVENT_LOG_TOPIC: &str = "/pillar/event-log/1.0.0";

/// The pillar-message format version this build EMITS on every encoded
/// [`overlay::MeshPeerRecord`] (ROI P1 "Versioning, compatibility & safe
/// rollout"). This surface's version space is INDEPENDENT of every other
/// stamped surface — notably the pillar-UDP wire version
/// ([`pillar_udp::PROTOCOL_VERSION`]) — and advances on its own schedule.
pub const MESSAGE_VERSION: pillar_crypto::SurfaceVersion = pillar_crypto::SurfaceVersion(1);

/// The OLDEST pillar-message format version this build can still decode. A
/// decoded leading version line outside `[MIN_MESSAGE_VERSION, MESSAGE_VERSION]`
/// is a distinct [`overlay::DecodeError::UnsupportedMessageVersion`] — set apart
/// from a malformed/garbage message so the future compatibility layer can
/// negotiate a newer peer rather than treat it as corruption.
pub const MIN_MESSAGE_VERSION: pillar_crypto::SurfaceVersion = pillar_crypto::SurfaceVersion(1);

/// The pillar-message N-1+ backward-compat window (ROI P1 "Compatibility
/// contract: check, negotiate, N-1+"): the max tolerated absolute difference
/// between two libp2p peers' DECLARED [`MESSAGE_VERSION`]s for their overlay
/// mesh exchange to be admitted, mirroring `specs/VersioningCompat.tla`'s
/// `Negotiate` guard.
pub const MESSAGE_COMPAT_WINDOW: pillar_crypto::CompatWindow = pillar_crypto::CompatWindow(0);

/// The stable surface name the pillar-message format negotiates under (a
/// [`pillar_crypto::DeclaredVersions`] key).
pub const MESSAGE_SURFACE: &str = "pillar-message";

/// Negotiate compatibility for the pillar-message surface between this
/// build's [`MESSAGE_VERSION`] and a libp2p peer's declared running version —
/// exchanged (e.g. via `identify`'s protocol/agent metadata or a dedicated
/// handshake payload) BEFORE the peer's [`overlay::MeshPeerRecord`]s are
/// trusted. Compatible pairs (within [`MESSAGE_COMPAT_WINDOW`]) link; an
/// incompatible pair is cleanly refused — distinct from
/// [`overlay::DecodeError::UnsupportedMessageVersion`], which gates a single
/// ALREADY-RECEIVED message's leading stamp rather than the peer relationship
/// itself.
///
/// # Errors
/// Returns [`pillar_crypto::NegotiationRefused`] when the two declared
/// versions differ by more than [`MESSAGE_COMPAT_WINDOW`].
pub fn negotiate_message_peer(
    remote_version: pillar_crypto::SurfaceVersion,
) -> Result<(), pillar_crypto::NegotiationRefused> {
    pillar_crypto::negotiate_surface(
        MESSAGE_SURFACE,
        MESSAGE_VERSION,
        remote_version,
        MESSAGE_COMPAT_WINDOW,
    )
}

/// Protocol name used for the Kademlia DHT instance run by Pillar nodes.
pub const KAD_PROTOCOL_NAME: &str = "/pillar/kad/1.0.0";

/// Returns the [`gossipsub::IdentTopic`] used for Pillar's event log.
pub fn event_log_topic() -> gossipsub::IdentTopic {
    gossipsub::IdentTopic::new(EVENT_LOG_TOPIC)
}

fn kad_config() -> kad::Config {
    kad::Config::new(
        libp2p::StreamProtocol::try_from_owned(KAD_PROTOCOL_NAME.to_string())
            .expect("static protocol name is valid"),
    )
}

fn new_kademlia(peer_id: PeerId) -> kad::Behaviour<kad::store::MemoryStore> {
    let mut kademlia =
        kad::Behaviour::with_config(peer_id, kad::store::MemoryStore::new(peer_id), kad_config());
    // Serve DHT queries from other peers, not just issue our own: without
    // this every node defaults to `Mode::Client` and silently refuses
    // inbound FIND_NODE requests, which makes discovery of a peer that is
    // only reachable through another node's routing table impossible.
    kademlia.set_mode(Some(kad::Mode::Server));
    kademlia
}

fn gossipsub_config() -> gossipsub::Config {
    gossipsub::ConfigBuilder::default()
        .validation_mode(gossipsub::ValidationMode::Strict)
        .build()
        .expect("static gossipsub config is valid")
}

fn gossipsub_behaviour(keypair: &Keypair) -> gossipsub::Behaviour {
    gossipsub::Behaviour::new(
        gossipsub::MessageAuthenticity::Signed(keypair.clone()),
        gossipsub_config(),
    )
    .expect("static gossipsub config is valid")
}

/// The behaviour run by a normal, directly-dialable Pillar node: gossipsub
/// event log, Kademlia discovery, and identify (so peers learn our
/// listen/observed addresses, which Kademlia needs to be useful).
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct EventBehaviour {
    /// Append-only event log broadcast.
    pub gossipsub: gossipsub::Behaviour,
    /// Peer discovery / bootstrap DHT.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange, required for Kademlia to learn dialable
    /// addresses of peers it hears about.
    pub identify: identify::Behaviour,
}

/// The behaviour run by a Pillar node acting as a relay (`libp2p::relay`
/// server side) for other nodes that cannot be dialed directly.
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct RelayServerBehaviour {
    /// Relays circuit-relay-v2 connections for other peers.
    pub relay: relay::Behaviour,
    /// Peer discovery / bootstrap DHT (relays participate in discovery too).
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange.
    pub identify: identify::Behaviour,
}

/// The behaviour run by a Pillar node that may need a relay to be reached
/// (e.g. because it sits behind a NAT): gossipsub + kademlia + identify, plus
/// the relay client and DCUtR (direct connection upgrade through relay) so a
/// relayed connection is upgraded to a direct hole-punched one whenever
/// possible.
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct RelayClientBehaviour {
    /// Append-only event log broadcast.
    pub gossipsub: gossipsub::Behaviour,
    /// Peer discovery / bootstrap DHT.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange.
    pub identify: identify::Behaviour,
    /// Relay client: lets us reserve a slot on a relay and dial/be-dialed
    /// through it via circuit-relay-v2.
    pub relay_client: relay::client::Behaviour,
    /// Direct connection upgrade through relay: attempts to upgrade a
    /// relayed connection to a direct (hole-punched) one.
    pub dcutr: dcutr::Behaviour,
}

fn identify_config(keypair: &Keypair) -> identify::Config {
    identify::Config::new("/pillar/id/1.0.0".to_string(), keypair.public())
}

/// Builds a [`Swarm`] running [`EventBehaviour`] (gossipsub + kademlia +
/// identify) over TCP and QUIC transports, using a freshly generated
/// identity.
///
/// This is the OPEN default: no pnet pre-shared key, TCP + QUIC both
/// available, free to dial/be-dialed by any peer that speaks the
/// `/pillar/kad` protocol. Use [`build_event_swarm_with_root`] to build a
/// node bound to a configured [`PrivateSwarmKey`] instead.
pub fn build_event_swarm(
    keypair: Keypair,
) -> Result<Swarm<EventBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    build_event_swarm_with_root(keypair, PrivateSwarmKey::disabled())
}

/// Builds a [`Swarm`] running [`EventBehaviour`] whose TRANSPORT is bound to
/// `root`'s configured [`PrivateSwarmKey`].
///
/// - `root.is_enabled() == false` (the public default): identical to
///   [`build_event_swarm`] — TCP + QUIC, open to any peer.
/// - `root.is_enabled() == true` (a configured private network root): the
///   swarm runs over TCP ONLY, wrapped in the libp2p pnet pre-shared-key
///   handshake ([`libp2p::pnet::PnetConfig`]) derived from the root. A peer
///   whose transport-level handshake carries a DIFFERENT (or no) key can
///   never complete the pnet XSalsa20 handshake at all — the connection is
///   refused below every higher protocol (noise, yamux, kademlia), so a
///   mismatched-root peer cannot even reach the point of speaking
///   `/pillar/kad` to probe the DHT. This is the "two swarms configured with
///   different roots do not discover each other" guarantee: it is enforced
///   by the pnet handshake refusing to complete, not by any DHT-level check.
///   QUIC is not offered in this mode: QUIC's own TLS handshake is not
///   pnet-wrapped by this crate, so admitting it would open a side channel
///   that bypasses the root check.
pub fn build_event_swarm_with_root(
    keypair: Keypair,
    root: PrivateSwarmKey,
) -> Result<Swarm<EventBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = match root.0 {
        None => libp2p::SwarmBuilder::with_existing_identity(keypair)
            .with_tokio()
            .with_tcp(
                tcp::Config::default(),
                noise::Config::new,
                yamux::Config::default,
            )?
            .with_quic()
            .with_other_transport(pillar_udp_boxed_transport)?
            .with_behaviour(|key| {
                let peer_id = key.public().to_peer_id();
                EventBehaviour {
                    gossipsub: gossipsub_behaviour(key),
                    kademlia: new_kademlia(peer_id),
                    identify: identify::Behaviour::new(identify_config(key)),
                }
            })?
            .build(),
        Some(key) => {
            let psk = PreSharedKey::new(key);
            libp2p::SwarmBuilder::with_existing_identity(keypair)
                .with_tokio()
                .with_other_transport(|kp| pnet_tcp_transport(kp, psk))?
                .with_behaviour(|key| {
                    let peer_id = key.public().to_peer_id();
                    EventBehaviour {
                        gossipsub: gossipsub_behaviour(key),
                        kademlia: new_kademlia(peer_id),
                        identify: identify::Behaviour::new(identify_config(key)),
                    }
                })?
                .build()
        }
    };
    Ok(swarm)
}

/// Builds a TCP transport wrapped in the pnet pre-shared-key handshake, then
/// noise-authenticated and yamux-multiplexed exactly like the open
/// [`build_event_swarm`]'s TCP leg — the only difference is the pnet layer
/// interposed BELOW noise, so a peer without the matching key never gets far
/// enough to attempt the noise handshake at all.
fn pnet_tcp_transport(
    keypair: &Keypair,
    psk: PreSharedKey,
) -> libp2p::core::transport::Boxed<(PeerId, StreamMuxerBox)> {
    let pnet_config = PnetConfig::new(psk);
    tcp::tokio::Transport::new(tcp::Config::default())
        .and_then(move |socket, _| pnet_config.handshake(socket))
        .upgrade(Version::V1Lazy)
        .authenticate(noise::Config::new(keypair).expect("static noise config is valid"))
        .multiplex(yamux::Config::default())
        .map(|(peer_id, muxer), _| (peer_id, StreamMuxerBox::new(muxer)))
        .boxed()
}

/// Builds the pillar-UDP libp2p transport, upgraded (Noise-authenticated,
/// yamux-multiplexed) exactly like the TCP/QUIC legs, so a node that calls
/// [`build_event_swarm`] binds/advertises/dials `…/udp/<port>/p-pillar`
/// addresses as an ADDITIONAL registered transport. This is the live wiring
/// deferred by `pillar-udp-transport-impl`: the raw datagram substrate now
/// composes with the [`pillar_udp`] mechanics module in a running swarm.
fn pillar_udp_boxed_transport(
    keypair: &Keypair,
) -> libp2p::core::transport::Boxed<(PeerId, StreamMuxerBox)> {
    PillarUdpTransport::new(keypair.clone())
        .upgrade(Version::V1Lazy)
        .authenticate(noise::Config::new(keypair).expect("static noise config is valid"))
        .multiplex(yamux::Config::default())
        .map(|(peer_id, muxer), _| (peer_id, StreamMuxerBox::new(muxer)))
        .boxed()
}

/// Builds a [`Swarm`] running [`RelayServerBehaviour`] over TCP, acting as a
/// circuit-relay-v2 relay for other Pillar nodes.
pub fn build_relay_server_swarm(
    keypair: Keypair,
) -> Result<Swarm<RelayServerBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_behaviour(|key| {
            let peer_id = key.public().to_peer_id();
            RelayServerBehaviour {
                relay: relay::Behaviour::new(peer_id, relay::Config::default()),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
            }
        })?
        .build();
    Ok(swarm)
}

/// Builds a [`Swarm`] running [`RelayClientBehaviour`] over TCP, with the
/// relay-client transport wired in so it can reserve a slot on / dial through
/// a relay and attempt DCUtR hole punching.
pub fn build_relay_client_swarm(
    keypair: Keypair,
) -> Result<Swarm<RelayClientBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_relay_client(noise::Config::new, yamux::Config::default)?
        .with_behaviour(|key, relay_client| {
            let peer_id = key.public().to_peer_id();
            RelayClientBehaviour {
                gossipsub: gossipsub_behaviour(key),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
                relay_client,
                dcutr: dcutr::Behaviour::new(peer_id),
            }
        })?
        .build();
    Ok(swarm)
}

/// Convenience: the [`PeerId`] a [`Keypair`] resolves to.
pub fn peer_id_of(keypair: &Keypair) -> PeerId {
    keypair.public().to_peer_id()
}

/// A federation seed peer: a well-known bootstrap node's dialable multiaddr
/// paired with the [`PeerId`] it terminates at.
///
/// Seeds are how a joining node enters Pillar's OWN Kademlia DHT — the swarm
/// that runs the `/pillar/kad/1.0.0` protocol, NOT the public IPFS DHT. Pillar
/// never seeds Kademlia with the public IPFS bootstrap nodes and never announces
/// itself as a public-IPFS provider, so the substrate is natively federation-
/// restricted: content is reachable only to peers that joined via a federation
/// seed. A seed is purely a discovery helper (it teaches the routing table where
/// to start); it is NOT a control plane — authority stays with the WoT.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SeedPeer {
    /// The seed's `PeerId` (parsed from the `/p2p/<id>` component of its
    /// multiaddr).
    pub peer_id: PeerId,
    /// The seed's dialable multiaddr WITHOUT the trailing `/p2p/<id>` — the
    /// address Kademlia stores for the peer.
    pub address: libp2p::Multiaddr,
}

/// A multiaddr offered as a federation seed did not carry a terminating
/// `/p2p/<peer-id>` component, so the peer it identifies is unknown and it
/// cannot be added to the routing table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SeedAddrMissingPeerId {
    /// The offending multiaddr, rendered for the error message.
    pub addr: String,
}

impl std::fmt::Display for SeedAddrMissingPeerId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "seed multiaddr {:?} has no /p2p/<peer-id> component; a federation seed \
             must name the peer it dials (e.g. /ip4/…/tcp/…/p2p/12D3Koo…)",
            self.addr
        )
    }
}

impl std::error::Error for SeedAddrMissingPeerId {}

/// Parses a federation seed multiaddr into its [`SeedPeer`] parts.
///
/// The multiaddr MUST terminate in a `/p2p/<peer-id>` component; that peer id
/// is what Kademlia keys its routing table on, and dialing an address with no
/// known peer id cannot populate the DHT. Returns [`SeedAddrMissingPeerId`] when
/// the `/p2p` component is absent.
pub fn parse_seed_multiaddr(addr: libp2p::Multiaddr) -> Result<SeedPeer, SeedAddrMissingPeerId> {
    use libp2p::multiaddr::Protocol;
    let rendered = addr.to_string();
    // The peer id lives in the LAST /p2p component; strip it off to get the
    // bare dial address Kademlia stores.
    let mut address = addr;
    let peer_id = match address.pop() {
        Some(Protocol::P2p(peer_id)) => peer_id,
        _ => return Err(SeedAddrMissingPeerId { addr: rendered }),
    };
    Ok(SeedPeer { peer_id, address })
}

/// Seeds a node's [`EventBehaviour`] Kademlia routing table with one or more
/// federation seed peers and kicks off a DHT bootstrap so the node actually
/// enters the swarm.
///
/// For each seed this adds the `(peer_id, address)` pair to Kademlia (so the
/// routing table is non-empty and the peer is dialable through the DHT) and
/// then issues a single `kademlia.bootstrap()` — the query that walks outward
/// from the seeds to fill the routing table with the rest of the federation.
///
/// Returns the number of seeds added. A bootstrap with an empty routing table
/// is a no-op, so this only calls `bootstrap()` when at least one seed was
/// added; the caller can treat a zero return as "no seeds configured — this is
/// itself a seed/first node".
pub fn seed_event_dht(swarm: &mut Swarm<EventBehaviour>, seeds: &[SeedPeer]) -> usize {
    for seed in seeds {
        swarm
            .behaviour_mut()
            .kademlia
            .add_address(&seed.peer_id, seed.address.clone());
    }
    if !seeds.is_empty() {
        // A bootstrap over an empty table errors (`NoKnownPeers`); we only get
        // here with at least one seed added, so it always has a peer to start
        // from. The error is still non-fatal — log-and-continue at the call
        // site — because a joining node retries discovery as peers appear.
        let _ = swarm.behaviour_mut().kademlia.bootstrap();
    }
    seeds.len()
}

/// A libp2p private-swarm (pnet) pre-shared key, OFF by default.
///
/// A pnet key XORs a per-connection stream cipher over every transport byte, so
/// only peers holding the SAME key can complete a handshake — a fully-closed
/// federation variant on top of the protocol-level restriction the `/pillar/kad`
/// protocol name and seed-only bootstrap already give.
///
/// This is Pillar's **network root**: the identity of the physical swarm a
/// node's packets can reach, completely distinct from a `cell` key (WoT/
/// identity genesis *within* whichever network the node joined — a private
/// network still has cells, authority is untouched by this value). The
/// public default (`disabled()` / [`PrivateSwarmKey::default`]) means the
/// well-known OPEN federation: [`build_event_swarm`] wires no pnet layer at
/// all, so any peer that knows a seed can join, matching the ROI's "public
/// pillar ships a well-known public root" default.
///
/// Configuring a root ([`PrivateSwarmKey::from_root_secret`]) derives a
/// pre-shared key from an operator-chosen secret and, threaded through
/// [`build_event_swarm_with_root`], makes the swarm's TRANSPORT itself
/// refuse any peer whose configured root differs: the pnet handshake below
/// noise/yamux never completes, so a mismatched-root peer never reaches far
/// enough to speak `/pillar/kad` — DHT membership is validated at the
/// transport layer, not by a higher-level check that a malicious/mismatched
/// peer could bypass. Every pillar node is inherently a seed node; there is
/// no separate seed daemon — standing up a private/app-specific network is
/// exactly "configure the same root on each node, then point each node at
/// one or more owned nodes as its `--seed`s" via the existing
/// `federation-seed-bootstrap` seed-dial mechanism ([`parse_seed_multiaddr`]
/// / [`seed_event_dht`]), reused unchanged.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PrivateSwarmKey(pub Option<[u8; 32]>);

impl PrivateSwarmKey {
    /// The default: no private-swarm key, i.e. the open, well-known public
    /// federation substrate.
    pub fn disabled() -> Self {
        Self(None)
    }

    /// Derives a private-swarm pre-shared key from an operator-configured
    /// network root secret (the `--network-root` / `PILLAR_NETWORK_ROOT`
    /// value).
    ///
    /// The derivation is a single SHAKE256 pass over the raw secret bytes,
    /// producing a fixed 32-byte pnet key: same root text always derives the
    /// SAME key (so every node an operator configures with that root secret
    /// converges on one pnet swarm), and two DIFFERENT root secrets derive
    /// two keys that are indistinguishable from independent random keys to
    /// the pnet handshake — there is no feasible way for a peer holding one
    /// root to derive or guess the pnet key of a different root, so a
    /// mismatched root is refused exactly as if the peer held no key at
    /// all. This is deliberately a plain hash (not a slow KDF like argon2):
    /// pnet is a network-membership gate, not a password store, and the
    /// "secret" here is expected to be a generated high-entropy value the
    /// operator distributes to their own nodes, not a guessable password.
    pub fn from_root_secret(root_secret: &str) -> Self {
        use sha3::digest::{ExtendableOutput, Update, XofReader};
        let mut hasher = sha3::Shake256::default();
        hasher.update(b"pillar-network-root-psk-v1");
        hasher.update(root_secret.as_bytes());
        let mut key = [0u8; 32];
        hasher.finalize_xof().read(&mut key);
        Self(Some(key))
    }

    /// Whether a pre-shared key is configured (a private network root).
    pub fn is_enabled(&self) -> bool {
        self.0.is_some()
    }
}

/// Optional decentralized overlay mesh: reliability resources (liveness), not
/// safety.
///
/// **INVARIANT**: the overlay is strictly additive on top of [`EventBehaviour`]
/// / [`RelayClientBehaviour`] / [`RelayServerBehaviour`] and must NEVER become
/// a bootstrap dependency of the substrate. Concretely: [`build_event_swarm`]
/// and friends never reference this module, and [`build_overlay_event_swarm`]
/// with `overlay_enabled: false` degrades to exactly the plain substrate
/// behaviour (see `substrate_bootstraps_with_overlay_disabled` in the tests
/// below). The overlay's own peer-mesh metadata (addresses/capabilities a
/// node advertises to the mesh) is NOT pushed over its own bespoke gossip
/// channel; it rides the existing streaming DB (`pillar_streamdb`) as
/// ordinary content-addressed ops, per the ROI's "metadata rides the
/// streaming DB" requirement — see [`MeshPeerRecord::encode`] /
/// [`MeshPeerRecord::decode`], which are the pure (de)serialization the
/// `pillar-streamdb` round-trip test in this crate's dev-dependencies drives
/// an [`pillar_streamdb`]-backed `Op` payload through.
pub mod overlay {
    use libp2p::{multiaddr::Multiaddr, PeerId};
    use std::str::FromStr;

    /// A mesh peer's advertised reachability: its [`PeerId`] plus every
    /// [`Multiaddr`] it wants the overlay to know about (its role in the
    /// decentralized headscale/Nebula-analog overlay).
    ///
    /// This is pure metadata with no network behaviour of its own — it is
    /// produced/consumed by whatever already-connected substrate transport
    /// (gossipsub, direct RPC, …) a node uses to publish to its stream; the
    /// overlay never needs its own bootstrap channel to exchange it.
    #[derive(Clone, Debug, PartialEq, Eq)]
    pub struct MeshPeerRecord {
        peer_id: PeerId,
        addresses: Vec<Multiaddr>,
    }

    impl MeshPeerRecord {
        /// Build a record for `peer_id` advertising `addresses`.
        #[must_use]
        pub fn new(peer_id: PeerId, addresses: Vec<Multiaddr>) -> Self {
            MeshPeerRecord { peer_id, addresses }
        }

        /// This record's [`PeerId`].
        #[must_use]
        pub fn peer_id(&self) -> PeerId {
            self.peer_id
        }

        /// The addresses this record advertises.
        #[must_use]
        pub fn addresses(&self) -> &[Multiaddr] {
            &self.addresses
        }

        /// Encode this record to bytes suitable as a `pillar_streamdb::Op`
        /// payload: a simple length-prefixed, dependency-free wire format
        /// (newline-delimited UTF-8 strings). The FIRST line is a
        /// [`crate::MESSAGE_VERSION`] stamp (its `Display`, e.g. `v1`),
        /// followed by the peer id then each multiaddr, so the metadata can
        /// ride any content-addressed op log without requiring
        /// `pillar-streamdb` (or any serde crate) as a runtime dependency of
        /// this crate. [`Self::decode`] parses and version-checks that leading
        /// stamp.
        #[must_use]
        pub fn encode(&self) -> Vec<u8> {
            // Leading pillar-message version stamp (`v1`), then the payload
            // lines. The stamp is validated at the head of `decode`.
            let mut lines = vec![crate::MESSAGE_VERSION.to_string(), self.peer_id.to_base58()];
            lines.extend(self.addresses.iter().map(std::string::ToString::to_string));
            lines.join("\n").into_bytes()
        }

        /// Decode a record previously produced by [`Self::encode`].
        ///
        /// The leading version line is validated first: a missing/garbage first
        /// line is the existing malformed [`DecodeError`] (`Empty` /
        /// `MalformedVersion`), while a legible-but-unknown FUTURE version is
        /// the distinct [`DecodeError::UnsupportedMessageVersion`] (via
        /// [`pillar_crypto::SurfaceVersion::check_supported`]).
        ///
        /// # Errors
        ///
        /// Returns [`DecodeError`] if `bytes` is not valid UTF-8, is empty, its
        /// leading version line is malformed or an unsupported version, its peer
        /// id line is not a valid [`PeerId`], or any subsequent line is not a
        /// valid [`Multiaddr`].
        pub fn decode(bytes: &[u8]) -> Result<Self, DecodeError> {
            let text = std::str::from_utf8(bytes).map_err(|_| DecodeError::NotUtf8)?;
            let mut lines = text.lines();
            // Head-of-decode version gate. The stamp is `vN` (Display); accept
            // both that and a bare decimal `N` for robustness. A first line that
            // parses to no version at all is malformed; a legible-but-unknown
            // FUTURE version is the distinct unsupported-version reject.
            let version_line = lines.next().ok_or(DecodeError::Empty)?;
            let raw = version_line.strip_prefix('v').unwrap_or(version_line);
            let version = raw
                .parse::<u16>()
                .map(pillar_crypto::SurfaceVersion)
                .map_err(|_| DecodeError::MalformedVersion)?;
            version
                .check_supported(crate::MIN_MESSAGE_VERSION, crate::MESSAGE_VERSION)
                .map_err(DecodeError::UnsupportedMessageVersion)?;
            let peer_id_line = lines.next().ok_or(DecodeError::Empty)?;
            let peer_id = PeerId::from_str(peer_id_line).map_err(|_| DecodeError::InvalidPeerId)?;
            let addresses = lines
                .map(|line| Multiaddr::from_str(line).map_err(|_| DecodeError::InvalidAddress))
                .collect::<Result<Vec<_>, _>>()?;
            Ok(MeshPeerRecord { peer_id, addresses })
        }
    }

    /// A [`MeshPeerRecord::decode`] failure.
    #[derive(Clone, Copy, Debug, PartialEq, Eq)]
    pub enum DecodeError {
        /// The payload was not valid UTF-8.
        NotUtf8,
        /// The payload was empty (no version / peer id line).
        Empty,
        /// The leading version line was not a well-formed version stamp at all
        /// (not `vN` / decimal `N`): a parse error, NOT an unknown version.
        MalformedVersion,
        /// The leading version line parsed cleanly but carries a pillar-message
        /// version outside `[MIN_MESSAGE_VERSION, MESSAGE_VERSION]` — most
        /// importantly a version NEWER than this build understands. Reported
        /// distinctly from the malformed variants so the future compatibility
        /// layer can negotiate a newer peer rather than treat it as corruption.
        UnsupportedMessageVersion(pillar_crypto::VersionError),
        /// The peer id line was not a valid [`PeerId`].
        InvalidPeerId,
        /// A subsequent line was not a valid [`Multiaddr`].
        InvalidAddress,
    }

    impl std::fmt::Display for DecodeError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            let msg = match self {
                DecodeError::NotUtf8 => "mesh peer record payload was not valid UTF-8",
                DecodeError::Empty => "mesh peer record payload was empty",
                DecodeError::MalformedVersion => {
                    "mesh peer record's leading version line was malformed"
                }
                DecodeError::UnsupportedMessageVersion(e) => {
                    return write!(
                        f,
                        "mesh peer record carried an unsupported message version: {e}"
                    )
                }
                DecodeError::InvalidPeerId => {
                    "mesh peer record's first line was not a valid PeerId"
                }
                DecodeError::InvalidAddress => "mesh peer record contained an invalid Multiaddr",
            };
            f.write_str(msg)
        }
    }

    impl std::error::Error for DecodeError {}
}

/// The behaviour run by a normal Pillar node with the OPTIONAL overlay mesh
/// enabled: exactly [`EventBehaviour`] (gossipsub event log, Kademlia
/// discovery, identify) plus a [`Toggle`]d UPnP/NAT-PMP behaviour that tries
/// to open a port mapping on the local gateway to reduce partition
/// frequency/duration.
///
/// The `upnp` field is a [`Toggle`], not a bare [`upnp::tokio::Behaviour`],
/// specifically so the overlay can be compiled in but runtime-disabled
/// without changing the behaviour type — this is what lets
/// [`build_overlay_event_swarm`] guarantee the substrate boots identically
/// whether or not the overlay is present.
#[derive(libp2p::swarm::NetworkBehaviour)]
pub struct OverlayEventBehaviour {
    /// Append-only event log broadcast.
    pub gossipsub: gossipsub::Behaviour,
    /// Peer discovery / bootstrap DHT.
    pub kademlia: kad::Behaviour<kad::store::MemoryStore>,
    /// Address/protocol exchange.
    pub identify: identify::Behaviour,
    /// Optional UPnP/NAT-PMP port mapping — the overlay's reliability
    /// resource. Disabled (`Toggle::from(None)`) leaves this behaviour
    /// entirely inert, at which point [`OverlayEventBehaviour`] behaves
    /// exactly like [`EventBehaviour`].
    pub upnp: Toggle<upnp::tokio::Behaviour>,
}

/// Builds a [`Swarm`] running [`OverlayEventBehaviour`]: the same substrate
/// as [`build_event_swarm`] (gossipsub + kademlia + identify) with the
/// optional overlay mesh's UPnP/NAT-PMP port mapping toggled by
/// `overlay_enabled`.
///
/// **INVARIANT**: with `overlay_enabled: false` this is behaviourally
/// identical to [`build_event_swarm`] — the substrate never requires the
/// overlay to bootstrap. See `substrate_bootstraps_with_overlay_disabled`.
pub fn build_overlay_event_swarm(
    keypair: Keypair,
    overlay_enabled: bool,
) -> Result<Swarm<OverlayEventBehaviour>, Box<dyn std::error::Error + Send + Sync>> {
    let swarm = libp2p::SwarmBuilder::with_existing_identity(keypair)
        .with_tokio()
        .with_tcp(
            tcp::Config::default(),
            noise::Config::new,
            yamux::Config::default,
        )?
        .with_quic()
        .with_behaviour(|key| {
            let peer_id = key.public().to_peer_id();
            let upnp = if overlay_enabled {
                Toggle::from(Some(upnp::tokio::Behaviour::default()))
            } else {
                Toggle::from(None)
            };
            OverlayEventBehaviour {
                gossipsub: gossipsub_behaviour(key),
                kademlia: new_kademlia(peer_id),
                identify: identify::Behaviour::new(identify_config(key)),
                upnp,
            }
        })?
        .build();
    Ok(swarm)
}

#[cfg(test)]
mod tests {
    use super::*;
    use futures::StreamExt;
    use libp2p::core::multiaddr::{Multiaddr, Protocol};
    use libp2p::swarm::SwarmEvent;
    use std::time::Duration;
    use tokio::time::timeout;

    fn local_tcp_listen_addr() -> Multiaddr {
        Multiaddr::empty()
            .with(Protocol::Ip4(std::net::Ipv4Addr::LOCALHOST))
            .with(Protocol::Tcp(0))
    }

    /// Drives `swarm` until `pred` returns `Some`, or the overall deadline
    /// elapses (in which case the test fails via `expect`).
    async fn drive_until<B: libp2p::swarm::NetworkBehaviour, T>(
        swarm: &mut Swarm<B>,
        deadline: Duration,
        mut pred: impl FnMut(&SwarmEvent<B::ToSwarm>) -> Option<T>,
    ) -> T {
        timeout(deadline, async {
            loop {
                let event = swarm.select_next_some().await;
                if let Some(v) = pred(&event) {
                    return v;
                }
            }
        })
        .await
        .expect("deadline elapsed waiting for expected swarm event")
    }

    async fn listen_and_get_addr<B: libp2p::swarm::NetworkBehaviour>(
        swarm: &mut Swarm<B>,
    ) -> Multiaddr {
        swarm.listen_on(local_tcp_listen_addr()).unwrap();
        drive_until(swarm, Duration::from_secs(10), |event| match event {
            SwarmEvent::NewListenAddr { address, .. } => Some(address.clone()),
            _ => None,
        })
        .await
    }

    /// Local multi-node swarm delivery: two [`EventBehaviour`] nodes connect
    /// directly, both subscribe to the event-log topic, and a message
    /// published by one is received by the other.
    #[tokio::test]
    async fn gossipsub_delivers_across_local_swarm() {
        let mut a = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let mut b = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let b_peer_id = *b.local_peer_id();

        let topic = event_log_topic();
        a.behaviour_mut().gossipsub.subscribe(&topic).unwrap();
        b.behaviour_mut().gossipsub.subscribe(&topic).unwrap();

        let b_addr = listen_and_get_addr(&mut b).await;
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        // Drive both swarms until gossipsub reports mesh subscription on both
        // sides (needed before publish reliably propagates over a mesh of
        // size 1) then publish and assert delivery.
        let deadline = Duration::from_secs(20);
        let drive_a = async {
            loop {
                if let SwarmEvent::Behaviour(EventBehaviourEvent::Gossipsub(
                    gossipsub::Event::Subscribed { .. },
                )) = a.select_next_some().await
                {
                    break;
                }
            }
        };
        let drive_b = async {
            loop {
                if let SwarmEvent::Behaviour(EventBehaviourEvent::Gossipsub(
                    gossipsub::Event::Subscribed { .. },
                )) = b.select_next_some().await
                {
                    break;
                }
            }
        };
        timeout(deadline, futures::future::join(drive_a, drive_b))
            .await
            .expect("both peers subscribed to the topic");

        a.behaviour_mut()
            .gossipsub
            .publish(topic.clone(), b"hello-pillar-event-log".to_vec())
            .expect("publish succeeds once mesh formed");

        let received = drive_until(&mut b, deadline, |event| match event {
            SwarmEvent::Behaviour(EventBehaviourEvent::Gossipsub(gossipsub::Event::Message {
                message,
                ..
            })) => Some(message.data.clone()),
            _ => None,
        })
        .await;
        assert_eq!(received, b"hello-pillar-event-log");
    }

    /// Kademlia discovery: two [`EventBehaviour`] nodes are bootstrapped
    /// against each other by address, and a `get_closest_peers` query from
    /// one successfully returns the other.
    #[tokio::test]
    async fn kademlia_discovers_peer() {
        let mut a = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let mut b = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let b_peer_id = *b.local_peer_id();

        let b_addr = listen_and_get_addr(&mut b).await;
        a.behaviour_mut()
            .kademlia
            .add_address(&b_peer_id, b_addr.clone());
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        // Keep `b` being polled in the background for the rest of the test
        // so it can accept the connection and answer `a`'s query.
        tokio::spawn(async move {
            loop {
                b.select_next_some().await;
            }
        });

        // Wait for the connection so the routing table entry is dialable.
        drive_until(&mut a, Duration::from_secs(10), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == b_peer_id => Some(()),
            _ => None,
        })
        .await;

        let query_id = a.behaviour_mut().kademlia.get_closest_peers(b_peer_id);

        let found = drive_until(&mut a, Duration::from_secs(15), |event| match event {
            SwarmEvent::Behaviour(EventBehaviourEvent::Kademlia(
                kad::Event::OutboundQueryProgressed {
                    id,
                    result: kad::QueryResult::GetClosestPeers(Ok(result)),
                    step,
                    ..
                },
            )) if *id == query_id && step.last => {
                Some(result.peers.iter().any(|p| p.peer_id == b_peer_id))
            }
            _ => None,
        })
        .await;
        assert!(
            found,
            "kademlia get_closest_peers should discover the bootstrapped peer"
        );
    }

    /// Relayed dial: a relay server node, plus two relay-client nodes `a`
    /// (the "reachable-only-via-relay" node) and `b` (the dialer). `a`
    /// listens through the relay's circuit-relay-v2 address; `b` dials `a`
    /// exclusively via that relayed address and the connection is
    /// established.
    #[tokio::test]
    async fn relayed_dial_succeeds() {
        let _ = tracing_subscriber::fmt()
            .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
            .try_init();
        let mut relay_swarm = build_relay_server_swarm(Keypair::generate_ed25519()).unwrap();
        let relay_peer_id = *relay_swarm.local_peer_id();
        let relay_addr = listen_and_get_addr(&mut relay_swarm).await;
        // The relay needs its own external address to include in reservation
        // responses, or it refuses reservations with `NoAddressesInReservation`.
        relay_swarm.add_external_address(relay_addr.clone());

        let mut a = build_relay_client_swarm(Keypair::generate_ed25519()).unwrap();
        let a_peer_id = *a.local_peer_id();
        let mut b = build_relay_client_swarm(Keypair::generate_ed25519()).unwrap();

        // `a` needs at least one (fake, for this loopback test) external
        // address to include in its relay reservation request, or the relay
        // refuses the reservation with `NoAddressesInReservation`.
        let a_tcp_addr = listen_and_get_addr(&mut a).await;
        a.add_external_address(a_tcp_addr);

        // Drive the relay server in the background for the whole test.
        tokio::spawn(async move {
            loop {
                relay_swarm.select_next_some().await;
            }
        });

        // `a` dials the relay directly, then listens on the relayed address
        // (reserving a slot on the relay for circuit-relay-v2).
        a.dial(relay_addr.clone().with(Protocol::P2p(relay_peer_id)))
            .unwrap();
        drive_until(&mut a, Duration::from_secs(10), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == relay_peer_id => {
                Some(())
            }
            _ => None,
        })
        .await;

        let relayed_listen_addr = relay_addr
            .clone()
            .with(Protocol::P2p(relay_peer_id))
            .with(Protocol::P2pCircuit);
        a.listen_on(relayed_listen_addr.clone()).unwrap();

        // Drive `a` until the relay confirms the reservation.
        let drive_a_reservation = async {
            loop {
                if let SwarmEvent::Behaviour(RelayClientBehaviourEvent::RelayClient(
                    relay::client::Event::ReservationReqAccepted { .. },
                )) = a.select_next_some().await
                {
                    break;
                }
            }
        };
        timeout(Duration::from_secs(10), drive_a_reservation)
            .await
            .expect("relay reservation accepted");

        // Keep driving `a` in the background so it can answer the incoming
        // relayed dial from `b`.
        tokio::spawn(async move {
            loop {
                a.select_next_some().await;
            }
        });

        // `b` dials `a` purely through the relay circuit address.
        let dial_addr = relay_addr
            .with(Protocol::P2p(relay_peer_id))
            .with(Protocol::P2pCircuit)
            .with(Protocol::P2p(a_peer_id));
        b.dial(dial_addr).unwrap();

        drive_until(&mut b, Duration::from_secs(20), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == a_peer_id => Some(()),
            _ => None,
        })
        .await;
    }

    /// INVARIANT under test: the overlay mesh must never be a bootstrap
    /// dependency of the substrate. A node built with
    /// `build_overlay_event_swarm(.., overlay_enabled: false)` must still
    /// bootstrap and run the same substrate protocols (gossipsub, kademlia)
    /// as plain [`build_event_swarm`] — with the overlay's UPnP behaviour
    /// entirely absent, not merely idle.
    #[tokio::test]
    async fn substrate_bootstraps_with_overlay_disabled() {
        let mut a = build_overlay_event_swarm(Keypair::generate_ed25519(), false).unwrap();
        let mut b = build_overlay_event_swarm(Keypair::generate_ed25519(), false).unwrap();
        let b_peer_id = *b.local_peer_id();

        // The overlay behaviour is disabled: no gateway search task is
        // spawned, so there is nothing overlay-related to wait on. Bootstrap
        // proceeds purely on the substrate (kademlia + identify), exactly as
        // it does for `build_event_swarm`.
        let b_addr = listen_and_get_addr(&mut b).await;
        a.behaviour_mut()
            .kademlia
            .add_address(&b_peer_id, b_addr.clone());
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        tokio::spawn(async move {
            loop {
                b.select_next_some().await;
            }
        });

        drive_until(&mut a, Duration::from_secs(10), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == b_peer_id => Some(()),
            _ => None,
        })
        .await;

        let query_id = a.behaviour_mut().kademlia.get_closest_peers(b_peer_id);
        let found = drive_until(&mut a, Duration::from_secs(15), |event| match event {
            SwarmEvent::Behaviour(OverlayEventBehaviourEvent::Kademlia(
                kad::Event::OutboundQueryProgressed {
                    id,
                    result: kad::QueryResult::GetClosestPeers(Ok(result)),
                    step,
                    ..
                },
            )) if *id == query_id && step.last => {
                Some(result.peers.iter().any(|p| p.peer_id == b_peer_id))
            }
            _ => None,
        })
        .await;
        assert!(
            found,
            "substrate (kademlia) must bootstrap fully with the overlay disabled"
        );
    }

    /// Mesh metadata round-trips through the streaming DB: a
    /// [`overlay::MeshPeerRecord`] survives `encode` -> [`pillar_streamdb::Op`]
    /// append -> gossip/merge into another node's log -> read back -> `decode`,
    /// unchanged. This is the "metadata rides the streaming DB" requirement:
    /// the overlay never gets its own bespoke metadata-gossip channel.
    #[test]
    fn mesh_metadata_round_trips_via_streaming_db() {
        use overlay::MeshPeerRecord;
        use pillar_streamdb::OpLog;

        let peer_id = PeerId::random();
        let addr_a: Multiaddr = "/ip4/127.0.0.1/tcp/4001".parse().unwrap();
        let addr_b: Multiaddr = "/ip4/198.51.100.7/udp/4002/quic-v1".parse().unwrap();
        let record = MeshPeerRecord::new(peer_id, vec![addr_a, addr_b]);

        // The node holding the record appends it to its stream (its slice of
        // the shared content-addressed op log).
        let mut publisher_log = OpLog::new();
        let op_id = publisher_log.append(record.encode());

        // Gossiped to another node exactly like any other op — pure CRDT
        // merge, no overlay-specific transport involved.
        let mut receiver_log = OpLog::new();
        receiver_log.merge(&publisher_log);
        assert!(receiver_log.contains(&op_id));

        // The receiver reads the op back out of its materialized order and
        // decodes it to the identical mesh peer record.
        let stored_op = receiver_log
            .order()
            .into_iter()
            .find(|op| op.id() == op_id)
            .expect("appended op is present in the materialized order");
        let decoded = MeshPeerRecord::decode(stored_op.payload())
            .expect("a record encoded by MeshPeerRecord::encode always decodes");
        assert_eq!(decoded, record);
    }

    /// A [`overlay::MeshPeerRecord`] round-trips carrying the current
    /// [`MESSAGE_VERSION`] stamp: the encoded form leads with the `v1` version
    /// line and decodes back to the identical record.
    #[test]
    fn mesh_record_round_trips_carrying_current_message_version() {
        use overlay::MeshPeerRecord;

        let peer_id = PeerId::random();
        let addr: Multiaddr = "/ip4/127.0.0.1/tcp/4001".parse().unwrap();
        let record = MeshPeerRecord::new(peer_id, vec![addr]);

        let encoded = record.encode();
        let first_line = std::str::from_utf8(&encoded)
            .unwrap()
            .lines()
            .next()
            .unwrap();
        assert_eq!(
            first_line,
            MESSAGE_VERSION.to_string(),
            "the encoded message leads with the current version stamp"
        );
        assert_eq!(MeshPeerRecord::decode(&encoded).unwrap(), record);
    }

    /// A message whose leading version line names a FUTURE pillar-message
    /// version is rejected distinctly as
    /// [`overlay::DecodeError::UnsupportedMessageVersion`] — NOT a malformed
    /// error. This is the case that lets the future compatibility layer treat a
    /// newer peer as negotiable rather than as corruption.
    #[test]
    fn mesh_record_future_message_version_is_rejected_distinctly() {
        use overlay::{DecodeError, MeshPeerRecord};

        let peer_id = PeerId::random();
        let record = MeshPeerRecord::new(peer_id, vec![]);
        let encoded = record.encode();

        // Replace the leading `v1` stamp with a FUTURE version, leaving the rest
        // of the (legible) message intact.
        let future = pillar_crypto::SurfaceVersion(MESSAGE_VERSION.0 + 1);
        let text = std::str::from_utf8(&encoded).unwrap();
        let mut lines: Vec<&str> = text.lines().collect();
        let future_line = future.to_string();
        lines[0] = &future_line;
        let bumped = lines.join("\n").into_bytes();

        let err = MeshPeerRecord::decode(&bumped).unwrap_err();
        assert_eq!(
            err,
            DecodeError::UnsupportedMessageVersion(pillar_crypto::VersionError::Unsupported {
                found: future,
                min: MIN_MESSAGE_VERSION,
                max: MESSAGE_VERSION,
            }),
        );
        assert_ne!(err, DecodeError::MalformedVersion);
    }

    /// A malformed / empty message is the parse error, NOT the
    /// unsupported-version error: an empty buffer is `Empty`, and a garbage
    /// leading version line is `MalformedVersion` — neither is
    /// `UnsupportedMessageVersion`.
    #[test]
    fn mesh_record_malformed_message_is_a_parse_error_not_unsupported() {
        use overlay::{DecodeError, MeshPeerRecord};

        // Empty payload: no version line at all.
        assert_eq!(MeshPeerRecord::decode(b"").unwrap_err(), DecodeError::Empty);

        // A garbage (non-`vN`) leading line is a malformed version, never an
        // unsupported version.
        let garbage = b"not-a-version\nsome-peer-id-line";
        let err = MeshPeerRecord::decode(garbage).unwrap_err();
        assert_eq!(err, DecodeError::MalformedVersion);
        assert!(
            !matches!(err, DecodeError::UnsupportedMessageVersion(_)),
            "a garbage version line is a parse error, not an unknown version"
        );
    }

    // --- pillar-message SESSION negotiation (two-sided peer handshake, ROI P1
    // "Compatibility contract: check, negotiate, N-1+") ---

    #[test]
    fn message_peer_negotiation_links_a_matching_peer() {
        assert!(negotiate_message_peer(MESSAGE_VERSION).is_ok());
    }

    #[test]
    fn message_peer_negotiation_links_within_the_compat_window() {
        let remote = pillar_crypto::SurfaceVersion(
            MESSAGE_VERSION.0.saturating_sub(MESSAGE_COMPAT_WINDOW.0),
        );
        assert!(negotiate_message_peer(remote).is_ok());
    }

    #[test]
    fn message_peer_negotiation_refuses_a_peer_outside_the_compat_window() {
        let remote = pillar_crypto::SurfaceVersion(MESSAGE_VERSION.0 + MESSAGE_COMPAT_WINDOW.0 + 1);
        let err = negotiate_message_peer(remote).unwrap_err();
        assert_eq!(err.surface, MESSAGE_SURFACE);
        assert_eq!(err.local, MESSAGE_VERSION);
        assert_eq!(err.remote, remote);
        assert_eq!(err.window, MESSAGE_COMPAT_WINDOW);
    }

    /// Pillar's Kademlia runs its OWN protocol, not the public IPFS DHT's, and
    /// is seeded with no bootstrap peers by default — so a freshly built node
    /// carries neither the public-IPFS protocol name nor the public IPFS
    /// bootstrap set. This is the federation-restriction invariant at the
    /// config layer.
    #[test]
    fn kademlia_uses_pillar_protocol_not_public_ipfs() {
        // The DHT protocol is Pillar's own, never the public IPFS `/ipfs/kad`.
        assert_eq!(KAD_PROTOCOL_NAME, "/pillar/kad/1.0.0");
        assert!(
            !KAD_PROTOCOL_NAME.starts_with("/ipfs/"),
            "pillar must not run the public IPFS DHT protocol"
        );

        // A freshly built node has an EMPTY routing table: no hardcoded
        // public-IPFS bootstrap nodes are ever added. `kbuckets` iterates the
        // routing table; on a fresh node it yields no entries.
        let mut swarm = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let entries: usize = swarm
            .behaviour_mut()
            .kademlia
            .kbuckets()
            .map(|b| b.num_entries())
            .sum();
        assert_eq!(
            entries, 0,
            "a fresh pillar node must carry no bootstrap peers (no public IPFS set)"
        );
    }

    /// A seed multiaddr with a terminating `/p2p/<id>` parses into its peer id
    /// and bare address; one without a `/p2p` component is rejected.
    #[test]
    fn seed_multiaddr_parsing() {
        let peer = PeerId::random();
        let full: Multiaddr = format!("/ip4/127.0.0.1/tcp/4001/p2p/{peer}")
            .parse()
            .unwrap();
        let parsed = parse_seed_multiaddr(full).expect("a /p2p seed parses");
        assert_eq!(parsed.peer_id, peer);
        assert_eq!(
            parsed.address,
            "/ip4/127.0.0.1/tcp/4001".parse::<Multiaddr>().unwrap()
        );

        let no_p2p: Multiaddr = "/ip4/127.0.0.1/tcp/4001".parse().unwrap();
        assert!(parse_seed_multiaddr(no_p2p).is_err());
    }

    /// The private-swarm key is OFF by default (the public root); a root
    /// secret derives a stable, deterministic key.
    #[test]
    fn private_swarm_key_is_off_by_default() {
        assert!(!PrivateSwarmKey::default().is_enabled());
        assert!(!PrivateSwarmKey::disabled().is_enabled());
        assert!(PrivateSwarmKey(Some([7u8; 32])).is_enabled());
    }

    /// The same root secret always derives the SAME pnet key (so every node
    /// an operator configures with that root converges on one swarm), and
    /// two different root secrets derive two different keys.
    #[test]
    fn root_secret_derivation_is_stable_and_distinct() {
        let a1 = PrivateSwarmKey::from_root_secret("my-private-network");
        let a2 = PrivateSwarmKey::from_root_secret("my-private-network");
        let b = PrivateSwarmKey::from_root_secret("a-different-network");
        assert!(a1.is_enabled());
        assert_eq!(a1, a2, "same root secret must derive the identical key");
        assert_ne!(a1, b, "different root secrets must derive different keys");
    }

    /// Federation join via a seed: a local seed peer listens, and a separate
    /// joining node — configured ONLY with the seed's multiaddr, never a raw
    /// dial — is seeded through [`seed_event_dht`], dials the seed, and enters
    /// the DHT (its routing table becomes non-empty and a discovery query
    /// resolves the seed).
    #[tokio::test]
    async fn joiner_enters_dht_via_seed_only() {
        // The seed / first node: listens, and is otherwise a plain event node.
        let mut seed = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let seed_peer_id = *seed.local_peer_id();
        let seed_addr = listen_and_get_addr(&mut seed).await;
        let seed_multiaddr = seed_addr.with(Protocol::P2p(seed_peer_id));

        // Keep the seed answering in the background for the rest of the test.
        tokio::spawn(async move {
            loop {
                seed.select_next_some().await;
            }
        });

        // The joiner: knows ONLY the seed multiaddr. Parse it and seed the DHT.
        let mut joiner = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let seeds = vec![parse_seed_multiaddr(seed_multiaddr).unwrap()];
        let added = seed_event_dht(&mut joiner, &seeds);
        assert_eq!(added, 1, "one seed configured");

        // The routing table must now be non-empty: the seed is in it.
        let entries: usize = joiner
            .behaviour_mut()
            .kademlia
            .kbuckets()
            .map(|b| b.num_entries())
            .sum();
        assert_eq!(
            entries, 1,
            "seeding must place the seed peer in the joiner's routing table"
        );

        // Driving the joiner: it dials the seed (the bootstrap query does) and
        // establishes a connection, then a discovery query resolves the seed —
        // proving it entered the DHT purely via the seed, with no raw --dial.
        drive_until(&mut joiner, Duration::from_secs(15), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == seed_peer_id => {
                Some(())
            }
            _ => None,
        })
        .await;

        let query_id = joiner
            .behaviour_mut()
            .kademlia
            .get_closest_peers(seed_peer_id);
        let found = drive_until(&mut joiner, Duration::from_secs(15), |event| match event {
            SwarmEvent::Behaviour(EventBehaviourEvent::Kademlia(
                kad::Event::OutboundQueryProgressed {
                    id,
                    result: kad::QueryResult::GetClosestPeers(Ok(result)),
                    step,
                    ..
                },
            )) if *id == query_id && step.last => {
                Some(result.peers.iter().any(|p| p.peer_id == seed_peer_id))
            }
            _ => None,
        })
        .await;
        assert!(
            found,
            "joiner configured only with the seed must enter the DHT and resolve it"
        );
    }

    /// The public-root default path is unchanged: [`build_event_swarm`] (no
    /// root configured) still bootstraps a real gossipsub + kademlia swarm,
    /// exactly as `gossipsub_delivers_across_local_swarm` /
    /// `kademlia_discovers_peer` already exercise. This proves
    /// [`build_event_swarm_with_root`] with a disabled root degrades to
    /// EXACTLY [`build_event_swarm`]'s behaviour — the private-root wiring is
    /// strictly additive.
    #[tokio::test]
    async fn public_root_default_path_unchanged() {
        let mut a =
            build_event_swarm_with_root(Keypair::generate_ed25519(), PrivateSwarmKey::disabled())
                .unwrap();
        let mut b = build_event_swarm(Keypair::generate_ed25519()).unwrap();
        let b_peer_id = *b.local_peer_id();

        let b_addr = listen_and_get_addr(&mut b).await;
        a.behaviour_mut()
            .kademlia
            .add_address(&b_peer_id, b_addr.clone());
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        tokio::spawn(async move {
            loop {
                b.select_next_some().await;
            }
        });

        drive_until(&mut a, Duration::from_secs(10), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == b_peer_id => Some(()),
            _ => None,
        })
        .await;

        let query_id = a.behaviour_mut().kademlia.get_closest_peers(b_peer_id);
        let found = drive_until(&mut a, Duration::from_secs(15), |event| match event {
            SwarmEvent::Behaviour(EventBehaviourEvent::Kademlia(
                kad::Event::OutboundQueryProgressed {
                    id,
                    result: kad::QueryResult::GetClosestPeers(Ok(result)),
                    step,
                    ..
                },
            )) if *id == query_id && step.last => {
                Some(result.peers.iter().any(|p| p.peer_id == b_peer_id))
            }
            _ => None,
        })
        .await;
        assert!(
            found,
            "the unconfigured (public) root path must still bootstrap/discover exactly as before"
        );
    }

    /// Two nodes configured with DIFFERENT network roots do NOT discover each
    /// other: the pnet pre-shared-key handshake mismatches below noise/yamux,
    /// so the transport-level connection never completes and no
    /// `ConnectionEstablished` event is ever produced on either side within a
    /// bounded window — proving the refusal happens at the pnet layer, not
    /// merely "the DHT query timed out for some other reason".
    #[tokio::test]
    async fn mismatched_roots_never_establish_a_connection() {
        let root_a = PrivateSwarmKey::from_root_secret("network-alpha");
        let root_b = PrivateSwarmKey::from_root_secret("network-beta");

        let mut a = build_event_swarm_with_root(Keypair::generate_ed25519(), root_a).unwrap();
        let mut b = build_event_swarm_with_root(Keypair::generate_ed25519(), root_b).unwrap();
        let b_peer_id = *b.local_peer_id();

        let b_addr = listen_and_get_addr(&mut b).await;
        a.dial(b_addr.with(Protocol::P2p(b_peer_id))).unwrap();

        // Drive both swarms concurrently for a bounded window: a matching-key
        // pair would establish a connection within a couple of seconds (see
        // `same_root_and_seed_converges_in_the_dht` below); a mismatched pair
        // must NOT, because the pnet handshake itself never completes.
        let drive_a = async {
            loop {
                if let SwarmEvent::ConnectionEstablished { .. } = a.select_next_some().await {
                    return true;
                }
            }
        };
        let drive_b = async {
            loop {
                if let SwarmEvent::ConnectionEstablished { .. } = b.select_next_some().await {
                    return true;
                }
            }
        };
        let raced = futures::future::select(Box::pin(drive_a), Box::pin(drive_b));
        let established = timeout(Duration::from_secs(5), raced).await;
        assert!(
            established.is_err(),
            "peers configured with DIFFERENT network roots must never establish a connection \
             (the pnet pre-shared-key handshake must refuse the mismatch)"
        );
    }

    /// Two nodes configured with the SAME private root, pointed at each other
    /// purely via `--seed` (never a raw `--dial`, and no public root/seed in
    /// their config), converge: the joiner's Kademlia routing table becomes
    /// non-empty and a discovery query resolves the seed — proving the
    /// private-root + seed combination is sufficient to stand up an
    /// independent swarm with the existing federation-seed-bootstrap
    /// mechanism, no new mechanism required.
    #[tokio::test]
    async fn same_root_and_seed_converges_in_the_dht() {
        let root = PrivateSwarmKey::from_root_secret("shared-private-root");

        let mut seed =
            build_event_swarm_with_root(Keypair::generate_ed25519(), root.clone()).unwrap();
        let seed_peer_id = *seed.local_peer_id();
        let seed_addr = listen_and_get_addr(&mut seed).await;
        let seed_multiaddr = seed_addr.with(Protocol::P2p(seed_peer_id));

        tokio::spawn(async move {
            loop {
                seed.select_next_some().await;
            }
        });

        let mut joiner = build_event_swarm_with_root(Keypair::generate_ed25519(), root).unwrap();
        let seeds = vec![parse_seed_multiaddr(seed_multiaddr).unwrap()];
        let added = seed_event_dht(&mut joiner, &seeds);
        assert_eq!(added, 1, "one seed configured");

        drive_until(&mut joiner, Duration::from_secs(15), |event| match event {
            SwarmEvent::ConnectionEstablished { peer_id, .. } if *peer_id == seed_peer_id => {
                Some(())
            }
            _ => None,
        })
        .await;

        let query_id = joiner
            .behaviour_mut()
            .kademlia
            .get_closest_peers(seed_peer_id);
        let found = drive_until(&mut joiner, Duration::from_secs(15), |event| match event {
            SwarmEvent::Behaviour(EventBehaviourEvent::Kademlia(
                kad::Event::OutboundQueryProgressed {
                    id,
                    result: kad::QueryResult::GetClosestPeers(Ok(result)),
                    step,
                    ..
                },
            )) if *id == query_id && step.last => {
                Some(result.peers.iter().any(|p| p.peer_id == seed_peer_id))
            }
            _ => None,
        })
        .await;
        assert!(
            found,
            "two nodes sharing the same private root, joined only via --seed, must converge in the DHT"
        );
    }
}
